### ISSUE TITLE
How to use a dust template from an external npm package in Kraken app?

### ISSUE THREAD

**Issue by mayyan** [krakenjs/kraken-js#134]
My page is composed of several components. For example I have footer component on the page:
```
<footer>
    {>"components/footer/footer" /}
</footer>
```
When `components/footer/footer.dust` is under `public/templates/`, it works fine.

Now, I want to externalize the components so that each of them is an NPM package. Let's say I have built a `footer` package. It includes everything for the footer, CSS, JS, and compiled dust template. At app-level, `footer` package is installed locally by `npm install footer`. 

How, at app-level, to embed the external footer template?

**Comment by jasisk** [comment]
Closing due to age and orthogonal to kraken.
