### ISSUE TITLE
Document 1.0 app.kraken.{get,set,use}

### ISSUE THREAD

**Issue by jeffharrell** [krakenjs/kraken-js#172]

**Comment by MHDMAM** [comment]
Hi @totherik I'm new to Krakenjs 1.0,
Trying to get port value from config using `app.kraken.get('server:port')` at `server.js`, but at that point i'm getting `get of undefined` even I set the option values
```js
options = {
  onconfig: function(config, next) {
   
    config.get('server:port').push(app);
    next(null, config);
  }
};
```
I missed something for sure, can you help on this please

**Comment by totherik** [comment]
Hey, @MHDMAM, well, unfortunately that's not a lot to go on. From what's here, if `config.js` looks something like
```json
{
    "server": {
        "port": [ 8080 ]
    }
}
```
...then it should work.

**Comment by MHDMAM** [comment]
Thanks @totherik 
Well, it pretty much look like that, I didn't change any thing in `server.js` just replace port number by `app.kraken.get('server:port')` 

But the app variable at that point look like:
``` js 
function (req, res, next) {
    app.handle(req, res, next);
  }
```

**Comment by pvenkatakrishnan** [comment]
@MHDMAM a few questions. 
* The code above looks like you are pushing the express app into `server:port` config. Is the interpretation correct. If yes what is the intention ?
* Have you tried `config.set` after you push your custom port into `server:port` config.

Also is there a repo that we can look at ?

**Comment by MHDMAM** [comment]
@pvenkatakrishnan I was trying to follow the get stared guide for KrakenJs.
I'v already defined the port value in `config.json`.
How/Where I can use `config.set` to get data from `config.json` before `.listen` method triggered?

I just start with `KrakenJs`, still scaffolding my project and I don't know what's the proper way to do the config thingy.

**Comment by lmarkus** [comment]
If I'm reading this correctly, it looks like @MHDMAM is simply trying to retrieve the `server:port` value from the configuration, so it can be passed to the `server.listen(PORT)` under `./server.js`

Probably something like this:
```javascript
'use strict';
var app = require('./index');
var http = require('http');

//Create and start HTTP server.
var server;
server = http.createServer(app);

//Try to retrieve port from config
var myPort = app.kraken.get('server:port'); //This fails because kraken is undefined at this point.
server.listen( myPort || process.env.PORT || 8000);

server.on('listening', function () {
    console.log('Server listening on http://localhost:%d', this.address().port);
});
```

One way to do this, is wait until the kraken app is running before trying to retrieve the config values.
App startup is completely independent from the  Server binding to a port, so this is valid:

```javascript
'use strict';
var app = require('./index');
var http = require('http');

//Create and start HTTP server.
var server;
server = http.createServer(app);

//Wait for app startup before retrieving config.
app.on('start',function(){
    var myPort = app.kraken.get('server:port'); //kraken is defined here.
    server.listen(myPort || process.env.PORT || 8000);
})

server.on('listening', function () {
    console.log('Server listening on http://localhost:%d', this.address().port);
});
```

Other suggestion on better ways of achieving this are welcome.

**Comment by totherik** [comment]
Yep, that pattern has been [described in other issues](https://github.com/krakenjs/kraken-js/issues/221#issuecomment-45354519). An alternative for port, specifically, would be to use env variables or [package.json config](https://docs.npmjs.com/files/package.json#config) for special values that need to be known before app config processing. Those can then be accessed via package.json directly or known env variables if that app is started via 'npm start'.
