### ISSUE TITLE
Intermittent crash dustjs template compilation in development

### ISSUE THREAD

**Issue by mikemliu** [krakenjs/kraken-js#270]
I'm experiencing intermittent crashes in development when loading dust templates client-side. Seems like some process is removing compilation artifacts before they are completely served...

```
Mon, 11 Aug 2014 17:58:43 GMT uncaughtException ENOENT, open '/path/to/root/tmp/templates/partials/path/to/partial.dust'
Error: ENOENT, open '/path/to/root/tmp/templates/partials/path/to/partial.dust'
```
Occasionally I would also see `ENOTEMPTY` when something is trying to call `rmdir` on a directory within `/project-root/tmp/`

Trying to isolate whether if this is in `kraken-devtools` or `engine-munger` but no luck yet. Any help appreciated... This is obviously not a deal-breaker in production but extremely annoying having to restart all the time in development.

**Comment by aredridel** [comment]
Closing - no response
