### ISSUE TITLE
grunt build doesn't product css files in .build/css/

### ISSUE THREAD

**Issue by digitalhomes** [krakenjs/kraken-js#287]
Tried grunt build in fresh kraken app.
Used LESS CSS pre-processor. 
Doesn't seem to produce css files.

**Comment by joeblau** [comment]
I figured out the problem.  You need migrate your version of less to 2.0:

http://lesscss.org/usage/#v2-upgrade-guide

`npm install -g less-plugin-clean-css` fixes the issue

**Comment by jasisk** [comment]
Whoa. This one fell off the radar. Appreciate the update, Joe. Closing this out but if the conversation needs to continue, feel free.
