### ISSUE TITLE
adaro broken template logging

### ISSUE THREAD

**Issue by brandonlai** [krakenjs/kraken-js#319]
Running my krakenjs app in NODE_ENV=production causes the following error.  It only happens once deployed.  Running locally in NODE_ENV=production doesn't produce the same error.  Is there a way to track down the template that causes this issue?

Wed, 14 Jan 2015 10:07:42 GMT uncaughtException Object [object Object] has no method 'p'
TypeError: Object [object Object] has no method 'p'
    at body_0 (undefined:1:149)
    at /var/lib/openshift/53f40f114382ec37cc0005e8/app-root/runtime/repo/node_modules/adaro/lib/patch/index.js:85:33
    at /var/lib/openshift/53f40f114382ec37cc0005e8/app-root/runtime/repo/node_modules/adaro/lib/reader/js.js:39:13
    at /var/lib/openshift/53f40f114382ec37cc0005e8/app-root/runtime/repo/node_modules/engine-munger/lib/munger.js:79:13
    at /var/lib/openshift/53f40f114382ec37cc0005e8/app-root/runtime/repo/node_modules/engine-munger/lib/cache.js:65:13
    at fs.js:266:14
    at /var/lib/openshift/53f40f114382ec37cc0005e8/app-root/runtime/repo/node_modules/engine-munger/node_modules/graceful-fs/graceful-fs.js:104:5
    at Object.oncomplete (fs.js:107:15)

**Comment by aredridel** [comment]
Look at your templates for ones that call `.p()` ?

Kind of hard to tell, though you could patch dust.onLoad to log the template name, I bet.

**Comment by brandonlai** [comment]
I think its a mismatch between my node versions.  Locally in my dev
environment had a different version of node than the deployment production
environment.  This lead to a mismatch in node_modules.  I am synching the
version on my dev box to match my deployment version.  Hopefully this will
resolve my issues since I push my .build into my git repo.

**Comment by aredridel** [comment]
Did that work?

**Comment by brandonlai** [comment]
Yes. After the development and production environment node versions we in synch everything worked again. The reason is I run grunt build and check in all my .build files before pushing to the production environment. There mush have been a breaking change in the compiled templates the the older production modules couldn't handle. 

Thanks for your support!

-Brandon
