### ISSUE TITLE
Bump meddleware dependency

### ISSUE THREAD

**Issue by oblador** [krakenjs/kraken-js#322]
`meddleware` is at 2.0 as of two months (maybe even 3.0 now, a bit puzzled by gitub vs npm inconsistencies). Time for a bump?

**Comment by jasisk** [comment]
You're absolutely right. In fact, that's a big priority for us right now. We want to make sure we've got our ducks in a row—need to make sure some of the supporting pieces like the website and generator are a little bit more fresh—but you can expect this to happen very soon.

**Comment by jasisk** [comment]
Feel free to remain subscribed to this issue and I'll update with progress.
