### ISSUE TITLE
missing something with routes and delivering a view?

### ISSUE THREAD

**Issue by ohNegative** [krakenjs/kraken-js#327]
I've been fooling around with some Javascript MVC frameworks and have mostly been using KeystoneJS which is very straight forward. A friend recommended KrakenJS, but I've been having some issues with the routes on a site I'm building.

I'm still puzzled how I'm supposed to deliver the view. In Keystone, they have a routes/index.js file where you put all your views like this:

```
// Setup Route Bindings
exports = module.exports = function(app) {
	
	// Views
	app.get('/', routes.views.index);
	app.get('/blog/:category?', routes.views.blog);
	app.get('/blog/post/:post', routes.views.post);
	app.all('/contact', routes.views.contact);
    app.all('/work', routes.views.work);
    app.all('/commercial', routes.views.commercial);
    app.all('/residential', routes.views.residential);

```

But I can's seem to find anything similar in KrakenJs files. Is there somewhere in the files where you're binding the routes to the views?

This is what I have right now and I'm getting a 404 error:

Here is the controller:

```
'use strict';

var AboutModel = require('../models/about');
module.exports = function (router) {
    var model = new AboutModel();
    router.get('/about', function (req, res) {            
        res.render('about', model);           
    });

};
```

And then the model:

```
'use strict';

module.exports = function AboutModel() {
    return {
        name: 'about'
    };
};
```

I'm sure this is something basic I'm missing, so any help is greatly appreciated!

Pete

**Comment by aredridel** [comment]
Sounds like what keystone is calling views there is what kraken calls handlers/controllers.

**Comment by aredridel** [comment]
Kraken uses `express-enrouten` to load the controllers and bind them to a URL in the router; from there, the controllers or handlers call `res.render`, which is what renders the view (template). 

You might be getting caught in terminology here, but it's hard to tell.

When you get your 404, what URL are you going to? And where is that file of handlers?

**Comment by ohNegative** [comment]
@aredridel  Thanks for the info. 

You'll have to walk me through this.

I have the express-enrouten in the list of dependencies in the package.json file. I also have the handlers which are located in the requireJS file:

```
handlers = {
            'require': function (mod) {
                if (mod.require) {
                    return mod.require;
                } else {
                    return (mod.require = context.makeRequire(mod.map));
                }
            },
            'exports': function (mod) {
                mod.usingExports = true;
                if (mod.map.isDefine) {
                    if (mod.exports) {
                        return (defined[mod.map.id] = mod.exports);
                    } else {
                        return (mod.exports = defined[mod.map.id] = {});
                    }
                }
            },
            'module': function (mod) {
                if (mod.module) {
                    return mod.module;
                } else {
                    return (mod.module = {
                        id: mod.map.id,
                        uri: mod.map.url,
                        config: function () {
                            return  getOwn(config.config, mod.map.id) || {};
                        },
                        exports: mod.exports || (mod.exports = {})
                    });
                }
            }
        };
```

I'm running this on my localhost and I'm trying to bring up the localhost:8000/about page which I thought since my controller is calling the res.render about Model:

```
'use strict';

var AboutModel = require('../models/about');
module.exports = function (router) {
    var model = new AboutModel();
    router.get('/about', function (req, res) {            
        res.render('about', model);           
    });

};
```
It would then render the view being called by the controller?

My only thought is I'm not finding the correct handlers for the routers? Or where are the routers located in the generator project?

Sorry, let me know if I'm not giving you enough information to work with. 

Thanks again for your help,


Pete

**Comment by aredridel** [comment]
Getting there! the 'handlers' that you pasted don't look relevant -- requirejs related, not server-side, not really part of kraken.

You're using a generated kraken app, made by our generator? If so, is this file:

```
'use strict';

var AboutModel = require('../models/about');
module.exports = function (router) {
    var model = new AboutModel();
    router.get('/about', function (req, res) {            
        res.render('about', model);           
    });

};
```

in the controllers directory, called `index.js` ?

**Comment by ohNegative** [comment]
Nope.

This is what I have in the index,js

```
'use strict';

var express = require('express');
var kraken = require('kraken-js');


var options, app;

/*
 * Create and configure application. Also exports application instance for use by tests.
 * See https://github.com/krakenjs/kraken-js#options for additional configuration options.
 */
options = {
    onconfig: function (config, next) {
        /*
         * Add any additional config setup or overrides here. `config` is an initialized
         * `confit` (https://github.com/krakenjs/confit/) configuration object.
         */
        next(null, config);
    }
};

app = module.exports = express();
app.use(kraken(options));
app.on('start', function () {
    console.log('Application ready to serve requests.');
    console.log('Environment: %s', app.kraken.get('env:env'));
});

```
i think this was the missing piece. So for every controller and model, I have to make sure I add this to the index.js file then?

Let me give this a try and let you know.

Thanks again,


Pete

**Comment by aredridel** [comment]
Almost! Each controller (or set of them) goes in a file inside `controllers/` -- for the root URL space, that'd be `controllers/index.js`. In there, one can register `/about` and have it work; if the file were called `controllers/foo/index.js` or `controllers/foo.js`, it would make URLs like `/foo/about` instead. `express-enrouten` is what sets up this mapping from filename to URL.

The `index.js` in the root of your app is different: that's the file that defines that app's entry, what actually loads kraken when it starts. Don't confuse them -- `controllers/index.js` is different than `index.js` in the root.

**Comment by ohNegative** [comment]
This is what I did originally. . . 

I added an about.js file to the controllers folder. . . 

```
'use strict';
var aboutModel = require('../models/about');
module.exports = function (router) {
    var model = new AboutModel();
    router.get('/about', function (req, res) {   
        res.render('about', model);
    });

};
```

and then a file to the models folder called about.js:

```
'use strict';
module.exports = function AboutModel() {
    return {
        name: 'about'
    };
};

```

then if I go to the localhost:8000/about it just errors and says "he URL /about did not resolve to a route."

here's a screenshot of what my files look like: http://i.imgur.com/gXiaTGL.jpg just in case you need to know if I'm putting this in the right place. 

Now I'm thinking I just have the url wrong?

Pete

**Comment by aredridel** [comment]
Yeah. An `about.js` that registers the route `/about` makes the URL `/about/about`.

If you want it to just be `/about`, change the file name to `index.js`

**Comment by ohNegative** [comment]
Or put it in the controllers/index.js file, since you can't have two index.js files in the controllers folder.

So I then deleted  both the about.js in the controllers folder and then the about.js in the models folder and kept them both in the index.js file for both the controllers and the models folder:

Index.js:

```
'use strict';


var IndexModel = require('../models/index');
module.exports = function (router) {
    var model = new IndexModel();
    router.get('/', function (req, res) { 
        res.render('index', model);    
    });

};

var aboutModel = require('../models/index');
module.exports = function (router) {
    var model = new AboutModel();
    router.get('/about', function (req, res) {   
      res.render('about', model);
               
    });

};

```

and then the models.js file:

```
'use strict';

module.exports = function IndexModel() {
    return {
        name: 'index'
    };
};

module.exports = function AboutModel() {
    return {
        name: 'about'
    };
};

```

Then I'm getting an uncaught exception that my AboutModel isn't defined? How do I reference the AboutModel in the index controller? I think this is it, once I have this, we should be good to go. I know we're covering more ground than lewis and clark here. lol

Pete

**Comment by aredridel** [comment]
Yeah, you're overwriting one export with the other: models files don't have to be all in one. Keep the models separate. (if you even need those files-- there's no reason you have to have a model file for each controller either)

**Comment by ohNegative** [comment]
ok - I think I got it now. . . 

This is what I did, although I'm back to getting the same error of my url is not resolving to a route.

So in the controllers folder, I created a folder "about" and then in that folder created the index.js file:

```
'use strict';

var AboutModel = require('../models/about');
module.exports = function (router) {
    var model = new AboutModel();
    router.get('/', function (req, res) {
        res.render('this is the about us page');
    });

};

```

Then I set up a separate model for the about page:

```
'use strict';

module.exports = function AboutModel() {
    return {
        name: 'about'
    };
};

```

screenshot here - http://imgur.com/ut7lY3y

With this setup, what would the url be for the about page be then?

**Comment by aredridel** [comment]
That should be `/about/` -- with the trailing slash.

**Comment by aredridel** [comment]
Also, your path to the models is wrong -- `"../../models/about"` if you move the file deeper like that.

**Comment by aredridel** [comment]
So just to clarify, what URL are you accessing? What error do you get? And do you get any errors when you start your app?

**Comment by ohNegative** [comment]
VICTORY!!!!

Yeah, the path on the models was wrong. As soon as I got the error when I started the server, I went back and updated the path to the models and everything is working good now.

Last last last last question, I swear. So in order to render the template, I need to have an about.dust template in the public template folders, and then reference it in the controller like so:

```
res.render('about', model);
```

And that will render the about.dust template - correct?

Thank you again for being so patient with me and helping through this. I'm really stoked I got this working now. 

Pete

**Comment by aredridel** [comment]
Yep! In development mode, that's all you need.

Once you want to make this a live app where lots of people hit it, you'd want to run `grunt build` and run the app in production mode: that puts the templates in the `.build` folder, and does localization and all that fun stuff. But long story short: "to run in production mode, run `grunt build` first."

**Comment by ohNegative** [comment]
Thanks for the heads up on the production build. Is this the same if I'm using Gulp as well?

If it is, you can close this issue out and thanks a ton for your help in clarifying some of this stuff, I learned a LOT more about how KrakenJs works now!!

Pete

**Comment by aredridel** [comment]
Yeah, you'll need to either run grunt and gulp, or port the kraken stuff to gulp -- the worst would be `grunt-localizr`, which would probably be much better in gulp.

Or have gulp run the grunt task through the gulp-grunt interface.

**Comment by ohNegative** [comment]
Sounds good. Thanks again for the help. I'm closing this issue out. 

Have a great weekend!

Pete
