### ISSUE TITLE
The router middleware,I want to exclude the .svn folders???

### ISSUE THREAD

**Issue by jerrywu55** [krakenjs/kraken-js#331]
I use svn manage my code.When I deploy on production env,svn will create .svn folder each dir.
And so I get error when run npm start.
So,have some method to exclude the special folders? Like .svn.
``
        "router": {
            "module": {
                "arguments": [{"directory": "path:./controllers"}]
            }
        }
``

Any helper will be greate appreciate.

**Comment by sixlettervariables** [comment]
This is actually handled by enrouten-express, and was fixed (but requires a version bump), see: https://github.com/krakenjs/express-enrouten/pull/58 and https://github.com/krakenjs/express-enrouten/pull/51 .

**Comment by jasisk** [comment]
Yup. @sixlettervariables is right.

That said, the new version of express-enrouten will be in kraken very soon.
