### ISSUE TITLE
can kraken support Socket.IO easily?  have documents or examples?

### ISSUE THREAD

**Issue by chelsh** [krakenjs/kraken-js#332]
can kraken support Socket.IO easily?  have documents or examples?
i only see 4 examples,but do not have socket:
Kraken Shopping Cart
Kraken Passport Integration
Localization and Internationalization
Specialization

**Comment by aredridel** [comment]
By socket, do you mean "TCP Socket", as `require('net')` provides, or WebSocket, as `ws` provides, or Socket.IO?

**Comment by chelsh** [comment]
Socket.IO  :)

**Comment by aredridel** [comment]
Yes, it can -- I think I'll spend some time tomorrow documenting; mostly, they don't interact -- you can tuck socket.io in `index.js` like you would with any express app, and access it the way you normally would.

**Comment by chelsh** [comment]
and passport.js  session also use in the socket.io? i see example:Kraken Passport Integration  use  app.use(passport.session());

**Comment by aredridel** [comment]
yep. That works about the same as Express too -- but making socket.io play nice with passport is a little hard, since they mostly ignore each other.

**Comment by chelsh** [comment]
OK,i will see your example:The project is at http://github.com/aredridel/socket-io-with-kraken as I've set it up

**Comment by aredridel** [comment]
Good luck!

**Comment by jasisk** [comment]
Closing this out due to inactivity. Feel free to continue the conversation if need be.
