### ISSUE TITLE
 npm install bcrypt  errors,my python version is 2.7

### ISSUE THREAD

**Issue by chelsh** [krakenjs/kraken-js#334]
```
 npm install bcrypt
-\|/-\|/-\|/--\|/-\|/-\
> bcrypt@0.7.8 install /home/rehu/code/rehu/node_modules/bcrypt
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/rehu/code/rehu/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
make: g++: Command not found
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 127
make: Leaving directory `/home/rehu/code/rehu/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/rehu/node-v0.12.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 2.6.18-274.el5
gyp ERR! command "node" "/home/rehu/node-v0.12.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rehu/code/rehu/node_modules/bcrypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 2.6.18-274.el5
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bcrypt"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rehu/code/rehu/npm-debug.log
```

**Comment by aredridel** [comment]
The important part of that error is this:

```
make: g++: Command not found
```

That means you don't have the gcc C++ compiler installed or available in your path. Add that and bcrypt should compile.

**Comment by chelsh** [comment]
when i change the python version to 2.4, the g++ is ok,but install bcrypt  say bcrypt need python 2.5-python 3.0

**Comment by aredridel** [comment]
Yeah, python 2.7 is required to run `node-gyp`.

How are you determining that `g++` is okay in that case?

Do you have `g++` in your path?

**Comment by chelsh** [comment]
[root@iZ28zudukwhZ rehu]# python -V
Python 2.7
[root@iZ28zudukwhZ rehu]# g++
-bash: g++: command not found
[root@iZ28zudukwhZ rehu]# rm -rf /usr/bin/python
[root@iZ28zudukwhZ rehu]# mv /usr/bin/python_old /usr/bin/python
[root@iZ28zudukwhZ rehu]# python -V
Python 2.4.3
[root@iZ28zudukwhZ rehu]# g++
-bash: g++: command not found
[root@iZ28zudukwhZ rehu]#

**Comment by chelsh** [comment]
[root@iZ28zudukwhZ rehu]# yum install g++
addons                                                   | 1.9 kB     00:00     
base                                                     | 1.1 kB     00:00     
epel                                                     | 3.7 kB     00:00     
extras                                                   | 2.1 kB     00:00     
updates                                                  | 1.9 kB     00:00     
Excluding Packages in global exclude list
Finished
Setting up Install Process
No package g++ available.
Nothing to do

**Comment by aredridel** [comment]
Yeah, so no `g++` either way, but with python 2.4, `node-gyp` fails sooner, so you get no error about `g++`.

Install `gcc-c++`. (the binary name `g++` is inside the `gcc-c++` package. Distributions split up the compiler oddly.)

**Comment by chelsh** [comment]
install gcc-c++ ？

**Comment by aredridel** [comment]
Yeah, the package you want in RHEL/CentOS is `gcc-c++`. `yum install gcc-c++`.

**Comment by chelsh** [comment]
my python version must be what？ 2.7？

**Comment by aredridel** [comment]
python 2, 2.7 or greater.

**Comment by chelsh** [comment]
[root@iZ28zudukwhZ rehu]# npm install bcrypt
-\|/-\|/-\|-\|/-\|
> bcrypt@0.7.8 install /home/rehu/code/rehu/node_modules/bcrypt
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/rehu/code/rehu/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
../src/bcrypt_node.cc: In destructor ‘virtual<unnamed>::baton_base::~baton_base()’:
../src/bcrypt_node.cc:54: error: ‘class v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >’ has no member named ‘Dispose’
../src/bcrypt_node.cc: At global scope:
../src/bcrypt_node.cc:128: error: variable or field ‘GenSaltAsync’ declared void
../src/bcrypt_node.cc:128: error: ‘uv_work_t’ was not declared in this scope
../src/bcrypt_node.cc:128: error: ‘req’ was not declared in this scope
../src/bcrypt_node.cc:128: error: expected ‘,’ or ‘;’ before ‘{’ token
../src/bcrypt_node.cc:137: error: variable or field ‘GenSaltAsyncAfter’ declared void
../src/bcrypt_node.cc:137: error: ‘uv_work_t’ was not declared in this scope
../src/bcrypt_node.cc:137: error: ‘req’ was not declared in this scope
../src/bcrypt_node.cc:137: error: expected ‘,’ or ‘;’ before ‘{’ token
../src/bcrypt_node.cc:429: error: expected `}' at end of input
../src/bcrypt_node.cc:128: warning: ‘<unnamed>::GenSaltAsync’ defined but not used
../src/bcrypt_node.cc:137: warning: ‘<unnamed>::GenSaltAsyncAfter’ defined but not used
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory `/home/rehu/code/rehu/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/rehu/node-v0.12.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 2.6.18-274.el5
gyp ERR! command "node" "/home/rehu/node-v0.12.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rehu/code/rehu/node_modules/bcrypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 2.6.18-274.el5
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bcrypt"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rehu/code/rehu/npm-debug.log
[root@iZ28zudukwhZ rehu]# python -V
Python 2.7
[root@iZ28zudukwhZ rehu]# node -v
v0.12.0

**Comment by chelsh** [comment]
why:(

**Comment by aredridel** [comment]
well nuts. Looks like that version of bcrypt doesn't work with node 0.12.0, since the V8 API has changed. Let me see if there's a new version.

**Comment by aredridel** [comment]
You will need to update to `bcrypt@0.8.1`.

**Comment by chelsh** [comment]
give me the github site of bcrypt , i search a lot

**Comment by aredridel** [comment]
It's in the npm registry: `npm install --save bcrypt@0.8`

**Comment by chelsh** [comment]
[root@iZ28zudukwhZ rehu]# npm install --save bcrypt@0.8
-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|
> bcrypt@0.8.1 install /home/rehu/code/rehu/node_modules/bcrypt
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/rehu/code/rehu/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
  COPY Release/bcrypt_lib.node
make: Leaving directory `/home/rehu/code/rehu/node_modules/bcrypt/build'
bcrypt@0.8.1 node_modules/bcrypt
├── bindings@1.0.0
└── nan@1.5.0

**Comment by chelsh** [comment]
it is ok now ,Thank you:):)

**Comment by aredridel** [comment]
You are welcome!

**Comment by mrmayfield** [comment]
Same error for me, upgrading the bcrypt version fixed it, thanks.

**Comment by reharik** [comment]
Hi, just as a follow up, apt-get install -y build-essential helped me.  It has the g++ compiler in it.

**Comment by huogerac** [comment]
FYI:
I had the same issue and I needed to update the npm and it worked.
```
npm install -g npm
```
