### ISSUE TITLE
unable to override configuration values through command line params

### ISSUE THREAD

**Issue by acatl** [krakenjs/kraken-js#336]
essentially what im trying to do is: 

having config.json as:

```json
{
  "foo" : "someDefaultValue" 
}
```

Trying to override the value through:
`node index.js --foo=overrideValue`

while looking into how `node_modules/kraken-js/node_modules/confit/index.js` gets executed, it does 
get overridden in the first time confit gets executed at  https://github.com/krakenjs/kraken-js/blob/v1.0.x/lib/config.js#L62 but on the second time by https://github.com/krakenjs/kraken-js/blob/v1.0.x/lib/config.js#L69 it gets overriden back to the ` "someDefaultValue"`, 

is this a known issue, am I missing something very basic on how confit is supposed to behave? 

this is big since what im trying to override is a value when the app is being executed on diff machines, with diff values, so just a dev specific value is not enough. 

please help :)

**Comment by jasisk** [comment]
Hey @acatl. Thanks for the issue. I'm taking a look at this now but you're definitely not missing anything. I added the double resolve behavior to enable resolving assets internal to kraken (namely, the favicon) but your assumptions for how it _should_ work _are_ correct.

**Comment by jasisk** [comment]
The required change was just [merged into the next version of confit](https://github.com/krakenjs/confit/tree/es6). The good news is this will land soon in confit.

This change will get rolled in to kraken 2.0.
