### ISSUE TITLE
yeoman can't find the kraken generator

### ISSUE THREAD

**Issue by tbassetto** [krakenjs/kraken-js#339]
I haven't used yeoman in a while but it's the recommend way to install and start using kraken according to your website. I used iojs 1.5.0 and yeoman 1.4.5 (latest version for both of them).

After using `npm install -g generator-kraken`, `yo kraken` gives me:

```
Error kraken

You don't seem to have a generator with the name kraken installed.
```

Same thing if I just use `yo`, it doesn't list the generator even if `generator-kraken` is installed globally.

**Comment by jasisk** [comment]
Hey @tbassetto.
I've tried to reproduce this but I've, so far, not been able. Are you still seeing this issue?

**Comment by tbassetto** [comment]
I dug a bit and found the issue: `kraken` needs to be installed globally too! That's wasn't obvious at first sight.

You should update the content on [http://krakenjs.com/#gettingstarted](Getting started) to say that new users should run `npm install -g yo kraken generator-kraken bower grunt-cli`. In the end, `generator-kraken` depends on `kraken` being installed but won't do it automatically :)
