### ISSUE TITLE
Throw 404 error on my own

### ISSUE THREAD

**Issue by toksea** [krakenjs/kraken-js#342]
Hi!

Can we throw a 404 error in our controller, like in a `router.param()` check, and render it in configured `fileNotFound` view?

I saw #159 mentioned this feature, but cannot find an example.

Thanks!

**Comment by jasisk** [comment]
A 404 isn't really an error, it's just the absence of resource that matches the request. Without trying, I bet you could simple tell Express to try the next matching route. If no other routes match, it will fall through to the 404.

You tell Express to try the next route with `next('route')` (mentioned in the "Route Handlers" section of the [routing guide for Express]((http://expressjs.com/guide/routing.html))).

**Comment by jasisk** [comment]
Closing but feel free to continue the discussion.
