### ISSUE TITLE
Dust template Error: ENOENT, open ... on Windows

### ISSUE THREAD

**Issue by kurdin** [krakenjs/kraken-js#343]
on Windows 8, any krakenjs 1.x app could not start, from examples or generated from yo, because path to Dust files invalid.

[>] cd C:\GitHub\
[>] npm install -g yo generator-kraken
... done...
[>] yo kraken HelloWorld
... done...
[>] cd HelloWorld
[>] npm install
[>] npm start

````console
Server listening on http://localhost:8000
Application ready to serve requests.
Environment: development
Error: ENOENT, open 'c:\GitHub\HelloWorld\public\templates\GitHub\HelloWorld\public\templates\errors\500.js'
````

template open file path is incorrect with doubling real path "GitHub\HelloWorld\public\templates\GitHub\HelloWorld\public\templates\" 

Any example from here has same error: https://github.com/krakenjs/kraken-examples

**Comment by kurdin** [comment]
Ok, this turns out to be a node.js bug. We used 0.11.14 version. If you have this problem, just upgrage to 0.11.16: http://nodejs.org/dist/v0.11.16/node-v0.11.16-x86.msi

**Comment by aredridel** [comment]
Oh goodness. Yeah, the unstable versions of node before 0.12 had some interesting quirks. Good to know!

**Comment by kurdin** [comment]
@aredridel Well, 0.11.x pretty stable on linux and OSX :)

**Comment by aredridel** [comment]
Stability in this case is interface stability: the guarantees it makes have changed subtly over time. In this case, boom with a certain race condition.

**Comment by jasisk** [comment]
@kurdin: now that the stable release for that branch is out, why not use that (0.12.0)?

**Comment by kurdin** [comment]
I did not try 0.12.0 but I cound not install 0.11.16 on our pre-production and production servers (centos 6.5) It requires new C++ library or something like that, I have error: ``node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by node)``

I guess I can try 0.12.0. Maybe it is time. I heard ``pm2`` do not work well with 0.12, but we moved to ``forever`` anyway.
