### ISSUE TITLE
how to use locale in the controllers

### ISSUE THREAD

**Issue by chelsh** [krakenjs/kraken-js#348]
i use kraken as the restful api,how to use locale?
example:
    db.UserAcceptTopic.findOne(condition).lean(true).exec(function(err,userTopic){
        if(err){
            res.json({result:0,message:err});
        }
        else{
            if(!userTopic){
                return  res.json({result:2,message:tip.topic.notExist});
            }
------------------------tip.topic.notExist : i can use the locale?

**Comment by chelsh** [comment]
how to use i18n in the *.js document? i know how to use in the *.dust document:)

**Comment by chelsh** [comment]
in the *.js document,how to use the value defined by .properties file?

**Comment by aredridel** [comment]
You'll want to use the `bundalo` library for that.
