### ISSUE TITLE
Make config path more flexible

### ISSUE THREAD

**Issue by dendril** [krakenjs/kraken-js#350]
Hey 

I'm building my own workflow/framework using krakenjs and I found a problem in how the project manage the generation of the configPath, specifically, I'll need to override the following [function](https://github.com/krakenjs/kraken-js/blob/735d737d1f41076b51760759e223d16f550961b2/lib/config.js#L47).

Could be possible to allows me to provide a callback instead of assume a default behavior?

Thanks!

**Comment by jasisk** [comment]
Curious if you can go into your workflow a bit? We can certainly consider this since most everything else is configurable but I'd like to understand your need a bit better.

**Comment by dendril** [comment]
Basically I'm building a extremely simple configuration of kraken + react for isomorphic webapps.

The directory layout is something like:

+ browser/
+ server/
    - config/
        - env/
          - dev.json
          - prod.json
        - config.json 
        - development.json

And I want to "namespace" kraken configurations:

+ server/
    - config/
        - env/
          - dev.json
          - prod.json
        - kraken/
          - config.json 
          - development.json

Defining as `basedir` the server directory. Basically that's why will be great if I can customize the path returned by the `configPath` function.

**Comment by gabrielcsapo** [comment]
published in https://github.com/krakenjs/kraken-js/releases/tag/2.2.0
