### ISSUE TITLE
Is there production config sample file?

### ISSUE THREAD

**Issue by mani95lisa** [krakenjs/kraken-js#353]
I'm not clear what's config for production is best, so any sample will be better.

Thanks!

**Comment by aredridel** [comment]
https://github.com/aredridel/womp/blob/master/config/config.json is pretty typical -- it's the output of the generator.

Specifically, you don't want devtools enabled nor do you want error stack traces sent to the user. Other than that, it's up to you!

**Comment by mani95lisa** [comment]
@aredridel thanks!
