### ISSUE TITLE
app.render fails to render custom helpers added via engine configuration

### ISSUE THREAD

**Issue by bryanspears** [krakenjs/kraken-js#354]
Transplanting comment from #157 

res.render() functions as expected for custom helpers.

I stumbled across this issue when I noticed that using app.render() does not seem to pick up custom helpers added via config. For example, any helpers specified like below do not appear to function when used via app.render().

Note: I tried multiple ways to reference the path, specifying in different config files (dev/prod, etc.), and the helpers would show in the various debugs I put in some of the modules, but output was always empty string for any calls to my custom helpers which work fine when called via res.render().

```
"view engines": {
        "js": {
            "module": "engine-munger",
            "renderer": {
                "method": "js",
                "arguments": [
                    {
                        "cache": false,
                        "helpers": ["path:./lib/my-custom-helpers"]
                    },
                    {
                        "views": "config:express.views",
                        "view engine": "config:express.view engine",
                        "specialization": "config:specialization",
                        "i18n": "config:i18n"
                    }
                ]
            }
        }
    },
```

**Comment by aredridel** [comment]
I can't replicate the problem -- however, I have helpers configured somewhat differently. You can see my example repo at https://github.com/aredridel/womp/commit/7ae49db6b7dd105f7649cf785075de9303217ea1

**Comment by aredridel** [comment]
Notably, there's an implicit `path:` in there, so you can just use `helpers: ["./lib/my-custom-helpers"]`

**Comment by bryanspears** [comment]
I figured it out. `res.locals` is not populated for res.app.render or req.app.render and the helper in question depended on a set value. To be clear: the helpers were being included correctly, but it's interesting how it silently failed and didn't output any of my debugging.

My current workaround: `merge(model, res.locals);` before calling `res.app.render`

**Comment by pvenkatakrishnan** [comment]
interesting. yeah express res.render merges the model and res.locals internally. https://github.com/strongloop/express/blob/master/lib/response.js#L929
`app.render` hence misses that step. Good catch.

**Comment by aredridel** [comment]
Ah! Yes! The app.render behavior doesn't use res.locals, because it's used without access to res at all usually.
