### ISSUE TITLE
How to output pretty html -----response html all in a line,how to let them not in a line

### ISSUE THREAD

**Issue by chelsh** [krakenjs/kraken-js#355]
![image](https://cloud.githubusercontent.com/assets/10752360/6864808/41f7b1fe-d4a1-11e4-99dd-5786ffd626ee.png)

**Comment by chelsh** [comment]
but the result in the Browser also in a line，the dust version is "dustjs-linkedin": "~2.3.4",

![image](https://cloud.githubusercontent.com/assets/10752360/6864836/8282455e-d4a1-11e4-94d0-c804c275c83b.png)

**Comment by lmarkus** [comment]
That should be the right way to do it...
Here's a quick example repo showing it in action:
https://github.com/lmarkus/whitespace/blob/master/index.js#L5

**Comment by jasisk** [comment]
This info is covered in the [dustjs wiki](https://github.com/linkedin/dustjs/wiki/Dust-Tutorial#Controlling_whitespace_suppression) as well. Note that, with v2.5.0, the method for preventing whitespace suppression changed.
