### ISSUE TITLE
websites which use kranken-js

### ISSUE THREAD

**Issue by mani95lisa** [krakenjs/kraken-js#364]
Hi, I'm thinking whether kranken-js is proper for website like www.prosper.com. 
I know paypal is using it, but I don't know where, could anyone tell me some of that?

I think if there is a kranken-js cases page would be better for new user.

Thanks!

**Comment by pvenkatakrishnan** [comment]
If you are asking what parts of paypal products are using krakenjs
* the logged in experience of www.paypal.com
* checkout experience
* the business users (vendors who use paypal for payment) experience 
* the login flows

are some of the highly trafficked ones. Apart from these we have many other relatively smaller internal and external apps using kraken within paypal. Last time i checked something like 50 web apps are on kraken and growing. All kraken apps are in the web tier.

**Comment by lmarkus** [comment]
@mani95lisa At its core you're simply working with express.

Kraken gives you some very nice features through its collection of modules, like environment aware configuration (ie: You can have one set of settings for development and another for production. Switching between them is seamless), out-of the-box security best practices,  the ability to easily localize your content (In case prosper.com uses multiple languages for customers) and some good structure for your projects. 

It also leverages dust (the linked-in fork) for templating (Although you can choose whatever you want), allowing you to create complex pages out of simpler building blocks.

My personal opinion, if you have several node/express teams working under the same umbrella it gives your projects consistency, and that for me is worth it's weight in gold.

Give it a spin, play with the examples :)

**Comment by mani95lisa** [comment]
@pvenkatakrishnan @lmarkus Thanks!
