### ISSUE TITLE
View error stack trace

### ISSUE THREAD

**Issue by xShirase** [krakenjs/kraken-js#370]
Hi, and sorry for the noob qquestion, I'm sure I'm just missing something obvious.
I can see that there's a commit that seems to address this issue here : https://github.com/krakenjs/kraken-js/commit/75c3cbab6b1e1b1a80dad5633ef079a4b635d088

But my question is, how can I see the stack trace anyway?

**Comment by aredridel** [comment]
Remove the 500 error handler (set it `enabled: false` in config.json), and run in dev mode (not production) -- Express's default error handler shows stack traces.

**Comment by xShirase** [comment]
Yup, that does it thanks!

**Comment by jasisk** [comment]
For what it's worth: not a noob question at all. We get this question all the time. We're deprecating that middleware soon because it causes so much confusion.

So no worries! :grinning:
