### ISSUE TITLE
Error: unsupported charset "UTF-8"

### ISSUE THREAD

**Issue by chelsh** [krakenjs/kraken-js#375]
Server-API-1 (err): could not read in file /var/www/Server-API/source/node_modules/kraken-js/node_modules/body-parser/lib/read.js for context
Server-API-1 (err): could not read in file /var/www/Server-API/source/node_modules/kraken-js/node_modules/body-parser/node_modules/raw-body/index.js for context
Server-API-1 (err): Error: unsupported charset "UTF-8"
Server-API-1 (err):     at /var/www/Server-API/source/node_modules/kraken-js/node_modules/body-parser/lib/read.js:72:15
Server-API-1 (err):     at /var/www/Server-API/source/node_modules/kraken-js/node_modules/body-parser/node_modules/raw-body/index.js:80:7
Server-API-1 (err):     at wrapped (/var/www/Server-API/source/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
Server-API-1 (err):     at process._tickCallback (node.js:442:13)

**Comment by jasisk** [comment]
Would appreciate a bit more info on this one. However, googling for that error message turned up [this comment](https://github.com/expressjs/body-parser/issues/76#issuecomment-78416449):
> an error like `Error: unsupported charset "UTF-8"` typically means your body-parser install is simply corrupted. You should `npm uninstall body-parser && npm cache clean && npm install body-parser` to see if that fixes the issue.

**Comment by jasisk** [comment]
Closing but feel free to continue the conversation if necessary.
