### ISSUE TITLE
krakenjs do not support : pm2 start index.js -i 2 ?

### ISSUE THREAD

**Issue by chelsh** [krakenjs/kraken-js#376]
------ "bcrypt": "^0.8.1";  node version:v0.12.0
when i use "pm2 start index.js",it is ok.
but when i use "pm2 start index.js -i 2",it is error.

logs:
ubuntu@:/data/Server-Manage-API/source$ pm2 start index.js -i 2
[PM2] Process index.js launched
┌──────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name │ id │ mode    │ pid   │ status │ restart │ uptime │ memory      │ watching │
├──────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ index    │ 7  │ cluster │ 29716 │ online │ 0       │ 0s     │ 19.246 MB   │ disabled │
│ index    │ 8  │ cluster │ 29718 │ online │ 0       │ 0s     │ 11.098 MB   │ disabled │
└──────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
ubuntu@:/data/Server-Manage-API/source$ pm2 logs
########### Starting streaming logs for [all] process
PM2: 2015-04-30 18:31:11: App name:index id:7 online
PM2: 2015-04-30 18:31:11: App name:index id:8 online
PM2: 2015-04-30 18:31:12: App name:index id:7 exited with code null
PM2: 2015-04-30 18:31:12: Starting execution sequence in -cluster mode- for app name:index id:7
PM2: 2015-04-30 18:31:12: App name:index id:8 exited with code null
PM2: 2015-04-30 18:31:12: Starting execution sequence in -cluster mode- for app name:index id:8
PM2: 2015-04-30 18:31:12: App name:index id:7 online
PM2: 2015-04-30 18:31:12: App name:index id:8 online
PM2: 2015-04-30 18:31:13: App name:index id:7 exited with code null
PM2: 2015-04-30 18:31:13: Starting execution sequence in -cluster mode- for app name:index id:7
PM2: 2015-04-30 18:31:13: App name:index id:8 exited with code null
PM2: 2015-04-30 18:31:13: Starting execution sequence in -cluster mode- for app name:index id:8
PM2: 2015-04-30 18:31:14: App name:index id:7 online
PM2: 2015-04-30 18:31:14: App name:index id:8 online
PM2: 2015-04-30 18:31:15: App name:index id:7 exited with code null
PM2: 2015-04-30 18:31:15: Starting execution sequence in -cluster mode- for app name:index id:7
PM2: 2015-04-30 18:31:15: App name:index id:8 exited with code null
PM2: 2015-04-30 18:31:15: Starting execution sequence in -cluster mode- for app name:index id:8
PM2: 2015-04-30 18:31:15: App name:index id:7 online
PM2: 2015-04-30 18:31:15: App name:index id:8 online
index-7 (err):     at Function.Module._load (module.js:312:12)
index-7 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:59:21)
index-7 (err):     at Module.require (module.js:364:17)
index-7 (err):     at require (module.js:380:17)
index-7 (err):     at bindings (/data/Server-Manage-API/source/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
index-7 (err):     at Object.<anonymous> (/data/Server-Manage-API/source/node_modules/bcrypt/bcrypt.js:3:35)
index-7 (err):     at Module._compile (module.js:456:26)
index-7 (err):     at Object.Module._extensions..js (module.js:474:10)
index-7 (err):     at Module.load (module.js:356:32)
index-7 (err): Error: /data/Server-Manage-API/source/node_modules/bcrypt/build/Release/bcrypt_lib.node: undefined symbol: node_module_register
index-7 (err):     at Module.load (module.js:356:32)
index-7 (err):     at Function.Module._load (module.js:312:12)
index-7 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:59:21)
index-7 (err):     at Module.require (module.js:364:17)
index-7 (err):     at require (module.js:380:17)
index-7 (err):     at bindings (/data/Server-Manage-API/source/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
index-7 (err):     at Object.<anonymous> (/data/Server-Manage-API/source/node_modules/bcrypt/bcrypt.js:3:35)
index-7 (err):     at Module._compile (module.js:456:26)
index-7 (err):     at Object.Module._extensions..js (module.js:474:10)
index-7 (err):     at Module.load (module.js:356:32)
index-8 (err):     at Function.Module._load (module.js:312:12)
index-8 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:59:21)
index-8 (err):     at Module.require (module.js:364:17)
index-8 (err):     at require (module.js:380:17)
index-8 (err):     at bindings (/data/Server-Manage-API/source/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
index-8 (err):     at Object.<anonymous> (/data/Server-Manage-API/source/node_modules/bcrypt/bcrypt.js:3:35)
index-8 (err):     at Module._compile (module.js:456:26)
index-8 (err):     at Object.Module._extensions..js (module.js:474:10)
index-8 (err):     at Module.load (module.js:356:32)
index-8 (err): Error: /data/Server-Manage-API/source/node_modules/bcrypt/build/Release/bcrypt_lib.node: undefined symbol: node_module_register
index-8 (err):     at Module.load (module.js:356:32)
index-8 (err):     at Function.Module._load (module.js:312:12)
index-8 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:59:21)
index-8 (err):     at Module.require (module.js:364:17)
index-8 (err):     at require (module.js:380:17)
index-8 (err):     at bindings (/data/Server-Manage-API/source/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
index-8 (err):     at Object.<anonymous> (/data/Server-Manage-API/source/node_modules/bcrypt/bcrypt.js:3:35)
index-8 (err):     at Module._compile (module.js:456:26)
index-8 (err):     at Object.Module._extensions..js (module.js:474:10)
index-8 (err):     at Module.load (module.js:356:32)
index-8 (err): Error: /data/Server-Manage-API/source/node_modules/bcrypt/build/Release/bcrypt_lib.node: undefined symbol: node_module_register
index-8 (err):     at Module.load (module.js:356:32)
index-8 (err):     at Function.Module._load (module.js:312:12)
index-8 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:59:21)
index-8 (err):     at Module.require (module.js:364:17)
index-8 (err):     at require (module.js:380:17)
index-8 (err):     at bindings (/data/Server-Manage-API/source/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
index-8 (err):     at Object.<anonymous> (/data/Server-Manage-API/source/node_modules/bcrypt/bcrypt.js:3:35)
index-8 (err):     at Module._compile (module.js:456:26)
index-8 (err):     at Object.Module._extensions..js (module.js:474:10)
index-8 (err):     at Module.load (module.js:356:32)
index-7 (err): Error: /data/Server-Manage-API/source/node_modules/bcrypt/build/Release/bcrypt_lib.node: undefined symbol: node_module_register
index-7 (err):     at Module.load (module.js:356:32)
index-7 (err):     at Function.Module._load (module.js:312:12)
index-7 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:59:21)
index-7 (err):     at Module.require (module.js:364:17)
index-7 (err):     at require (module.js:380:17)
index-7 (err):     at bindings (/data/Server-Manage-API/source/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
index-7 (err):     at Object.<anonymous> (/data/Server-Manage-API/source/node_modules/bcrypt/bcrypt.js:3:35)
index-7 (err):     at Module._compile (module.js:456:26)
index-7 (err):     at Object.Module._extensions..js (module.js:474:10)
index-7 (err):     at Module.load (module.js:356:32)
PM2: 2015-04-30 18:31:16: App name:index id:8 exited with code null
PM2: 2015-04-30 18:31:16: Starting execution sequence in -cluster mode- for app name:index id:8
PM2: 2015-04-30 18:31:16: App name:index id:7 exited with code null
PM2: 2015-04-30 18:31:16: Starting execution sequence in -cluster mode- for app name:index id:7
PM2: 2015-04-30 18:31:17: App name:index id:8 online
PM2: 2015-04-30 18:31:17: App name:index id:7 online
index-8 (err): Error: /data/Server-Manage-API/source/node_modules/bcrypt/build/Release/bcrypt_lib.node: undefined symbol: node_module_register
index-8 (err):     at Module.load (module.js:356:32)
index-8 (err):     at Function.Module._load (module.js:312:12)
index-8 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:59:21)
index-8 (err):     at Module.require (module.js:364:17)
index-8 (err):     at require (module.js:380:17)
index-8 (err):     at bindings (/data/Server-Manage-API/source/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
index-8 (err):     at Object.<anonymous> (/data/Server-Manage-API/source/node_modules/bcrypt/bcrypt.js:3:35)
index-8 (err):     at Module._compile (module.js:456:26)
index-8 (err):     at Object.Module._extensions..js (module.js:474:10)
index-8 (err):     at Module.load (module.js:356:32)
index-7 (err): Error: /data/Server-Manage-API/source/node_modules/bcrypt/build/Release/bcrypt_lib.node: undefined symbol: node_module_register
index-7 (err):     at Module.load (module.js:356:32)
index-7 (err):     at Function.Module._load (module.js:312:12)
index-7 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:59:21)
index-7 (err):     at Module.require (module.js:364:17)
index-7 (err):     at require (module.js:380:17)
index-7 (err):     at bindings (/data/Server-Manage-API/source/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
index-7 (err):     at Object.<anonymous> (/data/Server-Manage-API/source/node_modules/bcrypt/bcrypt.js:3:35)
index-7 (err):     at Module._compile (module.js:456:26)
index-7 (err):     at Object.Module._extensions..js (module.js:474:10)
index-7 (err):     at Module.load (module.js:356:32)
PM2: 2015-04-30 18:31:18: App name:index id:8 exited with code null
PM2: 2015-04-30 18:31:18: Starting execution sequence in -cluster mode- for app name:index id:8
PM2: 2015-04-30 18:31:18: App name:index id:7 exited with code null
PM2: 2015-04-30 18:31:18: Starting execution sequence in -cluster mode- for app name:index id:7
PM2: 2015-04-30 18:31:18: App name:index id:8 online
PM2: 2015-04-30 18:31:18: App name:index id:7 online
index-8 (err): Error: /data/Server-Manage-API/source/node_modules/bcrypt/build/Release/bcrypt_lib.node: undefined symbol: node_module_register
index-8 (err):     at Module.load (module.js:356:32)
index-8 (err):     at Function.Module._load (module.js:312:12)
index-8 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:59:21)
index-8 (err):     at Module.require (module.js:364:17)
index-8 (err):     at require (module.js:380:17)
index-8 (err):     at bindings (/data/Server-Manage-API/source/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
index-8 (err):     at Object.<anonymous> (/data/Server-Manage-API/source/node_modules/bcrypt/bcrypt.js:3:35)
index-8 (err):     at Module._compile (module.js:456:26)
index-8 (err):     at Object.Module._extensions..js (module.js:474:10)
index-8 (err):     at Module.load (module.js:356:32)
index-7 (err): Error: /data/Server-Manage-API/source/node_modules/bcrypt/build/Release/bcrypt_lib.node: undefined symbol: node_module_register
index-7 (err):     at Module.load (module.js:356:32)
index-7 (err):     at Function.Module._load (module.js:312:12)
index-7 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:59:21)
index-7 (err):     at Module.require (module.js:364:17)
index-7 (err):     at require (module.js:380:17)
index-7 (err):     at bindings (/data/Server-Manage-API/source/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
index-7 (err):     at Object.<anonymous> (/data/Server-Manage-API/source/node_modules/bcrypt/bcrypt.js:3:35)
index-7 (err):     at Module._compile (module.js:456:26)
index-7 (err):     at Object.Module._extensions..js (module.js:474:10)
index-7 (err):     at Module.load (module.js:356:32)
PM2: 2015-04-30 18:31:19: App name:index id:8 exited with code null
PM2: 2015-04-30 18:31:19: Starting execution sequence in -cluster mode- for app name:index id:8
PM2: 2015-04-30 18:31:19: App name:index id:7 exited with code null
PM2: 2015-04-30 18:31:19: Starting execution sequence in -cluster mode- for app name:index id:7
PM2: 2015-04-30 18:31:19: App name:index id:8 online
PM2: 2015-04-30 18:31:19: App name:index id:7 online
index-7 (err): Error: /data/Server-Manage-API/source/node_modules/bcrypt/build/Release/bcrypt_lib.node: undefined symbol: node_module_register
index-7 (err):     at Module.load (module.js:356:32)
index-7 (err):     at Function.Module._load (module.js:312:12)
index-7 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:59:21)
index-7 (err):     at Module.require (module.js:364:17)
index-7 (err):     at require (module.js:380:17)
index-7 (err):     at bindings (/data/Server-Manage-API/source/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
index-7 (err):     at Object.<anonymous> (/data/Server-Manage-API/source/node_modules/bcrypt/bcrypt.js:3:35)
index-7 (err):     at Module._compile (module.js:456:26)
index-7 (err):     at Object.Module._extensions..js (module.js:474:10)
index-7 (err):     at Module.load (module.js:356:32)
index-8 (err): Error: /data/Server-Manage-API/source/node_modules/bcrypt/build/Release/bcrypt_lib.node: undefined symbol: node_module_register
index-8 (err):     at Module.load (module.js:356:32)
index-8 (err):     at Function.Module._load (module.js:312:12)
index-8 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:59:21)
index-8 (err):     at Module.require (module.js:364:17)
index-8 (err):     at require (module.js:380:17)
index-8 (err):     at bindings (/data/Server-Manage-API/source/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
index-8 (err):     at Object.<anonymous> (/data/Server-Manage-API/source/node_modules/bcrypt/bcrypt.js:3:35)
index-8 (err):     at Module._compile (module.js:456:26)
index-8 (err):     at Object.Module._extensions..js (module.js:474:10)
index-8 (err):     at Module.load (module.js:356:32)
PM2: 2015-04-30 18:31:21: App name:index id:7 exited with code null
PM2: 2015-04-30 18:31:21: Starting execution sequence in -cluster mode- for app name:index id:7
PM2: 2015-04-30 18:31:21: App name:index id:8 exited with code null
PM2: 2015-04-30 18:31:21: Starting execution sequence in -cluster mode- for app name:index id:8
PM2: 2015-04-30 18:31:21: App name:index id:7 online
PM2: 2015-04-30 18:31:21: App name:index id:8 online

**Comment by jasisk** [comment]
Not sure why you're only seeing this with `-i 2` however it reads like a bad binary dependency. Recommend `rm -rf ./node_modules/` and `npm install`.

In any case, this is not a kraken issue so I'm closing this out.
