### ISSUE TITLE
res.render('score',{user:user});  why need so much time？

### ISSUE THREAD

**Issue by chelsh** [krakenjs/kraken-js#378]
![image](https://cloud.githubusercontent.com/assets/10752360/7444085/06d31798-f1a8-11e4-8b52-22bf39ce22a5.png)

**Comment by chelsh** [comment]
my code：
 app.get('/me/score',auth.isLogin,getMyScore);

var getMyScore=function(req,res){
    db.User.findOne({_id:req.user._id}).select({_id:1,scoreCount:1}).exec(function(err,user){
        if(err){
            console.error(err);
            return res.render('errors/500');
        }
        else{
            if(!user){

                return res.render('errors/404');
            }
            else{
                return res.render('score',{user:user});
            }

        }
    });
}

**Comment by jasisk** [comment]
Difficult to say without the complete picture. My guess: you're compiling templates on the fly (dynamically). If you precompile your templates, things should go more smoothly. If you've used the generator, you can precompile your assets with `grunt build` and you can run your application in production mode by setting the environment variable appropriately (`NODE_ENV=production npm start`).

**Comment by chelsh** [comment]
---i run the follow command  before i run my application in the production mode.
grunt.registerTask('build', [ 'less', 'i18n', 'copyto' ]);

**Comment by chelsh** [comment]
@jasisk   i must grunt build dust ? how to?

**Comment by aredridel** [comment]
`grunt build` should do it. Then start the app in production mode.

**Comment by chelsh** [comment]
grunt.registerTask('build', [ 'less', 'i18n', 'copyto' ]);  
this? how to grunt build dust?

**Comment by aredridel** [comment]
The shell command: `grunt build`.

**Comment by chelsh** [comment]
[ 'less', 'i18n', 'copyto' ] : this do not need another one? for example:[ 'dust','less', 'i18n', 'copyto' ])?

**Comment by aredridel** [comment]
Correct. The `i18n` task does that.

**Comment by aredridel** [comment]
(The default implementation: `    grunt.registerTask('i18n', [ 'clean', 'localizr', 'dustjs', 'clean:tmp' ]);`)

**Comment by chelsh** [comment]
OK  thank you:)
