### ISSUE TITLE
Is it possible to access current locale in dust template?

### ISSUE THREAD

**Issue by neocotic** [krakenjs/kraken-js#379]
I currently have the following hard-coded in my `master.dust` file:

``` html
<!DOCTYPE html>
<html lang="en">
```

If I'm to support multiple languages I should really have the `lang` attribute dynamically populated to correctly reflect the current locale. Unfortunately. I can't see how to do this in kraken and I've been unable to find any documentation on doing so.

If this is possible, I'd recommend that the generator also be updated to do this automatically for `master.dust`.

**Comment by aredridel** [comment]
It depends on which module you're using to choose the locale. Anything stored in `res.locals.context` though is available in the templates as `context.whatever`.

Which system is choosing the locale for you?

**Comment by neocotic** [comment]
I'm using Makarka. I currently only support en-US so I haven't created a specific router/middleware for changing the locale but I'd like to know how to do this so I can avoid having `en-US` hard-coded in my Dust templates.

**Comment by aredridel** [comment]
That sounds like race conditions in makara; some of the fixes in file-resolver and localizr may not have been backported into makara.

**Comment by aredridel** [comment]
I'd suggest using the more recent modules.

**Comment by neocotic** [comment]
Well, I just used the generator a few days ago so it should be pretty up-to-date. The problem I'm having is that I'm not exactly sure where I should be looking for the current locale (in middleware or in Dust context).

I'm not saying there's a bug. I'm basically just trying to understand exactly what I'd need to do to access the current locale inside a Dust template. I've just started playing around with Kraken over the weekend.

**Comment by aredridel** [comment]
Yeah, that part was actually left out of the generated project. PayPal has internal modules for picking up locale (with stupidly complex rules to satisfy some business requirements).

I've been suggesting using bcp47 and putting it in the context. Actually doing the mapping is left as an exercise to the reader -- see https://github.com/krakenjs/kraken-example-with-i18n for a trivial system.

**Comment by neocotic** [comment]
Thanks, that example project helped a lot!
