### ISSUE TITLE
"public" directory can change?  i use the version 1.1 and 1.2 in the "public" directory

### ISSUE THREAD

**Issue by chelsh** [krakenjs/kraken-js#382]
![image](https://cloud.githubusercontent.com/assets/10752360/7509967/c68f5eb0-f4c9-11e4-931a-e11cb274bf79.png)

**Comment by chelsh** [comment]
grunt.registerTask('build', [ 'less', 'i18n', 'copyto' ]);


when i run this command:
$ grunt build
Running "less:build" (less) task
>> Destination not written because no source files were found.
>> Destination not written because no source files were found.

**Comment by chelsh** [comment]
how to set variable of the file config.json :)

**Comment by aredridel** [comment]
What's the goal here? To change which directory based on a URL parameter, or on a header?

**Comment by chelsh** [comment]
the version of my application have version 1.1 and version
1.5, in version 1.5 it has different js ,css,.dust file from the version 1.1

**Comment by aredridel** [comment]
Yeah. Why not use `public` as the root, with URLs like `/public/1.1` mapping to the `1.1` folder?

**Comment by chelsh** [comment]
but when i render the dust ,how to get the dust?
my code:
  return res.render('/1.1/topic',{topic:resultObj,locale:res.locals.context.locality});

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/7518217/43cead12-f50c-11e4-9334-be4616286342.png)

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/7518368/0cfd063e-f50d-11e4-9d38-dcf00af33bdd.png)

**Comment by aredridel** [comment]
That is more complex. You may want to consider sub-apps to have separate configurations for adaro/engine-munger/etc for each version.

**Comment by aredridel** [comment]
The alternative is to have a structure like `public/templates/1.1/template.dust`, then you can  `render('1.1/template')`.

**Comment by aredridel** [comment]
Or you can edit all the grunt tasks, and duplicate them for each separate set of templates for the localizr/dustjs production build, and set up separate kraken devtools for each public, and set up three static server middlewares. It's a lot of restructuring to have completely independent public folders.

**Comment by chelsh** [comment]
not "public/templates/1.1/template.dust" ,  it is "public/1.1/templates/template.dust"  in my code

**Comment by aredridel** [comment]
Correct. I'm suggesting using a different layout to work more easily with a single instance of the tools.

**Comment by chelsh** [comment]
but,the js ,css are all different in the version 1.1 and version 1.2

**Comment by aredridel** [comment]
Yes. You'd need to namespace those, too. Either as is or changing `version/type` to `type/version`.

**Comment by chelsh** [comment]
change the directory like the follow? and then can use render('1.1/template')?  
![image](https://cloud.githubusercontent.com/assets/10752360/7518851/092fc8b8-f510-11e4-9849-7bb3251f5074.png)

**Comment by aredridel** [comment]
No: 

```
public/
    templates/
        1.1/
             dust files here
        1.5/
             dust files here
     js/
          1.1/
              js files here, etc.
```

Though depending on what tools you're using in the rest of the stack, the non-template parts of the re-arrangement may not be needed.

**Comment by chelsh** [comment]
OK,let me have a try

**Comment by jasisk** [comment]
Though I'm with @aredridel that the original question deserves a little reconsideration, to answer the question for posterity:

``` json
// config/*.json
{
    "middleware": {
        "static": {
            "module": {
                "arguments": [ "path:./somewhereElse" ]
            }
        }
    }
}
```

**Comment by chelsh** [comment]
"arguments": [ "path:./somewhereElse" ]// can use variable？ because of  in version 1.1 it is "path:./public/1.1",and  in version 1.5 it is "path:./public/1.5"

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/7519611/d472a592-f513-11e4-93c5-30a91db2676e.png)

 my code in the controllers: return res.render('/1.1/topic',{topic:resultObj,locale:res.locals.context.locality});

logs:Error: Failed to lookup view "errors/500" in views directory "/code/Server-API2/public/templates"

**Comment by chelsh** [comment]
@aredridel @jasisk

**Comment by aredridel** [comment]
Correct. If you change the name of the error views, the error handling middleware you are using will need to be updated accordingly.

**Comment by chelsh** [comment]
return res.render('/1.1/topic',{topic:resultObj,locale:res.locals.context.locality});

this code run with the error,so go to find the errors/500.dust.
why this code run with error?:(

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/7520047/795e6e68-f516-11e4-87d6-b2d138e7ae71.png)

return res.render('/1.1/haha',{topic:resultObj,locale:res.locals.context.locality});

--logs:Error: Failed to lookup view "errors/500" in views directory "/Users/whw/code/Server-API2/public/templates"

**Comment by aredridel** [comment]
I don't know what your error is there -- the error view will display it if you fix the error handler.

**Comment by chelsh** [comment]
config.json can be dynamic setted? i want to set the "static" paramer of the  config.json  in my coder.

**Comment by aredridel** [comment]
You can update the config with `config.set`, but I don't think you want want you think you want. Instantiating new static middlewares -- or altering the configuration of one live, if that's even possible with its implementation -- can have very strange consequences under concurrency. Requests don't start and end in the same tick, and changing it midstream could be very confusing.

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/7529670/ced2fcc6-f56e-11e4-98b9-5632cb03c129.png)

**Comment by chelsh** [comment]
in onconfig function  how to set "static" paramer ,i want to set "path"="public/1.1" or "path"="public/1.5"  dynamic.
----
"static" - serves static files from a specific folder
Priority - 40
Module - "serve-static" (npm)
Arguments (Array)
String - local path to serve static files from (default: "path:./public")

**Comment by aredridel** [comment]
Yeah, you don't want to do that. Changing the value after the middleware is instantiated won't do anything. It's never referred to again.

**Comment by chelsh** [comment]
But how I joined version subdirectory in the public directory：（

**Comment by chelsh** [comment]
public/
    templates/
        1.1/
             dust files here
        1.5/
             dust files here
     js/
          1.1/
              js files here, etc.


－－－Use this method？

**Comment by aredridel** [comment]
I do suggest that method, yes.

**Comment by chelsh** [comment]
can not dynamically change the “path” parameter？
![image](https://cloud.githubusercontent.com/assets/10752360/7529793/7fa45e36-f570-11e4-8b65-90dfbe7b2590.png)

**Comment by aredridel** [comment]
https://github.com/expressjs/serve-static is the implementation.

Imagine this:

```
var config = { "path": "/public" };
var static = serveStatic(config.path);
config.path = "/other";
```

There is no way for the change on the third line to affect the value on line 2. Just because you can change the value in the config doesn't mean anyone is listening and cares.

**Comment by chelsh** [comment]
OK，i know~Thank you,i will try this method:
public/
templates/
1.1/
dust files here
1.5/
dust files here
js/
1.1/
js files here, etc.


-----but i try this method 10 hours ago,it is error,it may not find the haha.dust:
my code:return res.render('/1.1/haha',{topic:resultObj,locale:res.locals.context.locality});

--logs:Error: Failed to lookup view "errors/500" in views directory "/Users/whw/code/Server-API2/public/templates"

**Comment by aredridel** [comment]
Yes. Why are you versioning error templates?

**Comment by chelsh** [comment]
it is ok now .
return res.render('/1.1/haha',{topic:resultObj,locale:res.locals.context.locality}); //  not ok
return res.render('1.1/haha',{topic:resultObj,locale:res.locals.context.locality});//   ok

**Comment by aredridel** [comment]
Yep! You will want `public/templates/errors/500.dust` though, and the other error templates outside the versioning.

**Comment by chelsh** [comment]
Thank you very much @aredridel :)

**Comment by aredridel** [comment]
You are welcome.

**Comment by chelsh** [comment]
have one problem:
my code :grunt.registerTask('build', [ 'less', 'i18n', 'copyto' ]);
MacBook-Pro:Server-API2 $ grunt build
Running "less:build" (less) task
>> Destination not written because no source files were found.
>> Destination not written because no source files were found.

**Comment by aredridel** [comment]
And where did you move your less files?

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/7530196/da8bdb0c-f576-11e4-9b79-7328ca97e21f.png)

**Comment by aredridel** [comment]
Oh that is interesting. Not sure why `tasks/less.js` isn't picking that up. In theory, it matches its glob.

**Comment by chelsh** [comment]
do you know how to set ?,let tasks/less.js can do

**Comment by aredridel** [comment]
In `tasks/less.js`, does your configuration look like so:

```
       build: {
              options: {
                  cleancss: false
              },
              build: {
                  files: [{
                      expand: true,
                      cwd: 'public/css',
                      src: ['**/*.less'],
                      dest: '.build/css/',
                      ext: '.css'
                  }]
              }
        }
```

particularly the `build` object inside the `build` object?

If so, remove the wrapper like so:

```
       build: {
              options: {
                  cleancss: false
              },
              files: [{
                 expand: true,
                 cwd: 'public/css',
                 src: ['**/*.less'],
                 dest: '.build/css/',
                 ext: '.css'
             }]
            }
```

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/7530382/cf250452-f579-11e4-9d0c-116c11a47f2a.png)

**Comment by aredridel** [comment]
Yes. Look in `tasks/less.js`

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/7530439/f0954948-f57a-11e4-906a-6ad181aa0967.png)

**Comment by chelsh** [comment]
it is ok now，Thank you:):):0

**Comment by aredridel** [comment]
You are welcome! Sorry for the bug -- that's https://github.com/krakenjs/generator-kraken/issues/111 but not fixed in the version you used!

**Comment by chelsh** [comment]
OK:)

**Comment by aredridel** [comment]
I'm going to close this issue. Feel free to open another if you've other questions.

**Comment by chelsh** [comment]
OK～

**Comment by chelsh** [comment]
<div id="wrap">
        <footer id="footer">
            <div class="logo">
                <img src="/img/1.1/logo.png" >
                <div class="text">
                    <h2>{topic.title}</h2>
                    <span>{@pre type="content" key="subTitle"/}</span>
                </div>
            </div>
            <a class="download" href="" >{@pre type="content" key="download"/}</a>
        </footer>
    </div>



－－－render this dust，it is error

**Comment by chelsh** [comment]
“ <div id="wrap">
        <footer id="footer">
            <div class="logo">
                <img src="/img/1.1/logo.png" >
                <div class="text">
                    <h2>{topic.title}</h2>
                    <span>{@pre type="content" key="subTitle"/}</span>
                </div>
            </div>
            <a class="download" href="" >{@pre type="content" key="download"/}</a>
        </footer>
    </div> ”



－－－render this dust，it is error

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/7531692/3764a39a-f590-11e4-8bfa-5a25a97c3b80.png)




－－－render this dust，it is error

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/7531786/6683d12c-f591-11e4-99d7-361e32b3d603.png)


--when i remove all {@pre   }, and render this dust ,it is ok

**Comment by chelsh** [comment]
it is ok now , the "locales" directory must include version 1.1 and 1.5, like this:
![image](https://cloud.githubusercontent.com/assets/10752360/7532053/f1d46b1c-f594-11e4-84c2-10ceff0caf3e.png)

**Comment by aredridel** [comment]
Yep. Lots of the internal tools map things 1:1. I'm working on changing that for future revisions, but the current versions assume 1:1 maps.
