### ISSUE TITLE
Cross Origin Request Ajax Call to API Endpoint Lusca CSRF 

### ISSUE THREAD

**Issue by subunits** [krakenjs/kraken-js#383]
I am a developer trying to create an external endpoint using Krakenjs and Lusca CSRF.
How do I pass headers using an external rest ajax call or from a rest client application?
________________________________________________________
    POST /api-certification/api HTTP/1.1
    Content-Type: application/json
    Accept: application/json
    Host: localhost:8000
    Connection: close
    User-Agent: Paw/2.2.1 (Macintosh; OS X/10.10.3) GCDHTTPRequest
    Content-Length: 15
    Body:
    {"name":"test"}
______________________________________________________
Thanks!

**Comment by aredridel** [comment]
If this is on a domain where there is no browser access to this API -- never any cookies or other implicit authorization -- then there's no CSRF attack to worry about and you can disable CSRF protection.

CSRF protection is only needed when there is implicit authorization made in a browser.
