### ISSUE TITLE
Why session config cannot disable? 

### ISSUE THREAD

**Issue by jerrywuz** [krakenjs/kraken-js#384]
I set enabled : "false" , but it still load session middleware.

**Comment by jerrywuz** [comment]
"session": {
      "enabled": false
    }

**Comment by aredridel** [comment]
Kraken 1 loads middleware even when disabled, because the middleware is runtime switchable. This is a feature nobody uses.

Kraken 2 removes this, and just completely doesn't load unused middleware. The list of incompatible changes is very small, so you may want to try kraken 2 rc.
