### ISSUE TITLE
How to run browserify

### ISSUE THREAD

**Issue by mac10688** [krakenjs/kraken-js#389]
I'm trying to use browserify with krakenjs. I've been searching for some time
```javascript
module.exports = function (grunt) {

    // Load the project's grunt tasks from a directory
    require('grunt-config-dir')(grunt, {
        configDir: require('path').resolve('tasks')
    });

    // Register group tasks
    grunt.registerTask('build', [ 'jshint', 'less', 'browserify', 'i18n', 'copyto' ]);
    grunt.registerTask('test', [ 'jshint', 'mochacli' ]);

};
```
I see that browserify is listed.

```javascript
'use strict';


module.exports = function browserify(grunt) {
	// Load task
	grunt.loadNpmTasks('grunt-browserify');

	// Options
	return {
		build: {
			files: {
				'.build/js/app.js': ['public/js/app.js'],
			},
			options: {}
		}
	};
};
```

It looks to already be configured but I don't know what the files object is for.. I don't have a build folder but I am not able to get this to work. I've tried many things but nothing has worked. Can someone explain to me how this is supposed to work? Later I will want to use babel as well, so I want to learn in a way so that I can add more plugins later. I just haven't seen how to do this in the documentation.

I'm new nodejs so I hope there's not a gross oversight.

**Comment by aredridel** [comment]
What happens when you try to make it work?

Adding babel and browserify together is fun times. Both really want to own the process, you've got some plumbing work ahead of you. You might want webpack instead -- there's more built around that combination as yet.

What that task defines is that `.build/js/app.js` is built from the browserify entry point `public/js/app.js` -- that's it. It's up to browserify to find the rest.

You should be able to run `grunt build` to trigger your browserify as you've written it.

What happens instead?

**Comment by mac10688** [comment]
That seems to be what I want. Should this be documented or is this common grunt knowledge? If it would be sensible to document this and I figure out how it works I'll try to do that for you if you like. If not, then thanks for the advice.

I have family over so I can't test a lot of things out, but I'll see how and if I can get it to all work together.

Also, there's no other place to put this but I love the Krakenjs framework. I just have to figure out how it works, but I've tested a lot of frameworks that didn't suite my style, but krakenjs is perfect.

**Comment by aredridel** [comment]
It's common grunt knowledge, but that certainly doesn't preclude documenting it! We can do better, just have to figure out where to document it.

**Comment by aredridel** [comment]
And glad you like it! We're happy with it!

**Comment by mac10688** [comment]
I noticed the ticket isn't closed so I thought I would send an update. I'm taking your advice and checking out webpack. I read the first few pages and I still have a vague idea about what it's doing so I'm sure it'll take me a day or two more to wrap my head around things.

My goal is to create a project that can use:
Reactjs
Browserify
Babeljs
Iojs
Krakenjs

I think krakenjs will allow me the flexibility to use these other plugins, I just have to realize it.

Thanks again for your reply and as long as this ticket remains open, I'll report back on my findings.

**Comment by aredridel** [comment]
Nice! You're definitely picking tools that work together -- browserify and babel being perhaps the hardest to integrate. But doable!

Kraken certainly is that flexible. Don't confuse the generator's suggestions for How Things Must Be -- Kraken is mostly small components that are very flexible. The generator just suggests ways that works for us at PayPal.

**Comment by mac10688** [comment]
This will take me over a month to get through. I'm going to close this. The original question was answered. I'll still be looking to do a write up when I figure out how to configure webpack with all those other technologies. I'm definitely still investigating.

**Comment by joshbedo** [comment]
Has anyone got babel to work with the browserify task yet? I was trying to get the babelify transform working but they don't seem to play well together.

**Comment by aredridel** [comment]
You may want to open another issue -- hijacking closed ones generally gets lost since there's no tracking.
