### ISSUE TITLE
working with the nodejs Benchmarking WG

### ISSUE THREAD

**Issue by trevnorris** [krakenjs/kraken-js#393]
An official Benchmarking WG has been created for the nodejs foundation (information on https://github.com/nodejs/benchmarking). We are investigating ways to more thoroughly detect performance regression over different versions. Part of this has been discussion around using larger scale benchmarks, instead of relying so heavily on the micro benchmarks commonly used.

I'm reaching out to larger and heavily used projects to hopefully get participation in creating mock realistic use cases that can be used to test node throughout the development process. Would anyone like to participate by either helping us write the benchmarks or pointing to existing suitable cases?

**Comment by jasisk** [comment]
I'll talk to some of the other folks around here—including some of the folks doing a lot of the internal monitoring, etc—but you can definitely count is in. I'll get some names over to the WG after I can ask around a bit.

**Comment by aredridel** [comment]
+1. Definitely paying attention even if I'm not the one working on it!

**Comment by tlivings** [comment]
Definitely would like to contribute!

**Comment by trevnorris** [comment]
@jasisk Thanks. Would be great to get that feedback.
