### ISSUE TITLE
How to submit a form using dustjs with csrf

### ISSUE THREAD

**Issue by mickyloranger** [krakenjs/kraken-js#394]
Hi,

I'm learning krakenjs (version 1.0.5). I want to process a user registration and login but have the an error: "... Error: CSRF token mismatch.". <input type="hidden" name="_csrf" value="<%= _csrf %>"/> is already includes my forms. How to process the post request in controller? 

Thanks for your help

Achille

**Comment by jasisk** [comment]
You'll need to submit the csrf token with each POST.

The easiest way is to include a `hidden` form element with the token. You can access the token in the template as `_csrf`.

Something like the following:
``` html
<form method="post">
  <input type="hidden" name="_csrf" value="{_csrf}">   <!-- this is the important line -->
  <label for="email">Email: <input name="email" id="email"></label>
  <input type="submit" name="submit" value="Save">
</form>
```

That said, you can also submit the token as a header for things like ajax posts. The readme should be able to guide you in that.

Closing this out, but feel free to keep asking questions in this thread. :grinning:

**Comment by mickyloranger** [comment]
thanks i change <%= _csrf %> to {_csrf} and the post can be now sending without CSRF token mismatch.
