### ISSUE TITLE
Examples for configuration

### ISSUE THREAD

**Issue by am2064** [krakenjs/kraken-js#395]
As it is now, your configuration documentation tells you what the file expects with no examples of how to write a good configuration. This seems important as you don't have a consistent format on configuration.

For example, 

* `"multipart"` - parses multipart FORM bodies
  - Priority - 80
  - Module - `"kraken-js/middleware/multipart"` (delegates to [formidable](https://www.npmjs.org/package/formidable))
  - Arguments (*Array*)
      - *Object*
        - `"encoding"` (*String*) - sets encoding for incoming forms
        - `"uploadDir"` (*String*) - sets the directory for placing file uploads in
        - `"keepExtensions"` (*Boolean*) - if you want the files written to the `uploadDir` to include extensions of the original file, set this property to `true`
        - `"maxFieldsSize"` (*Number*) - limits the amount of memory all fields together (except files) can allocate in bytes
        - `"maxFields"` (*Number*) - limits the number of fields that the querystring parser will decode
        - `"hash"` (*String*) - if you want checksums calculated for incoming files, set this to either `"sha1"` or `"md5"`
        - `"multiples"` (*Boolean*) - if this option is enabled, `req.files` will contain arrays of files for inputs which submit multiple files using the HTML5 `multiple` attribute

Could have an example such as

```
,"multipart": {
        "arguments":
        [
                {
                        "uploadDir":"./tmp"
                }
        ]
}
```

to show how to handle the odd notation of 
  - Arguments (*Array*)
      - *Object*

**Comment by aredridel** [comment]
@grawk You may be interested in this -- this example is from debugging an app on IRC today, discovered this doc hole.

**Comment by aredridel** [comment]
You may want to use "path:tmp" (use a shortstop handler to have an app-relative path)

**Comment by aredridel** [comment]
and if you override the block, override the WHOLE block from the default config is my advice

**Comment by grawk** [comment]
To clarify: the ask is that the docs include an example of an override in addition to the indented description of the default middleware?

**Comment by am2064** [comment]
Pretty much, yeah. Thats about right @grawk . It caused me confusion long enough to complain on IRC about it haha.

**Comment by aredridel** [comment]
Yeah. Just need more detail on "how to configure". From the fact that there is a default configuration to how to override it.

**Comment by grawk** [comment]
That makes perfect sense to me! Thanks.

**Comment by berlincityboy** [comment]
Is this way of configuring still up-to-date? For instance, I just tried to configure the multipart middleware following the given scheme in the README. This resulted in a config which does not work:

"middleware": {
    "multipart": {
      "enabled": true,
      "priority": 0,
      "module": "kraken-js/middleware/multipart",
       "arguments": [
         {
           "uploadDir": "/tmp/upload",
           "keepExtensions": true,
           "hash": "sha1",
           "multiples": false
         }
       ]
    }
}

It cost a lot of time to figure out that this is the way to go:

"middleware": {
    "multipart": {
      "enabled": true,
      "priority": 0,
      "module": {
        "name": "kraken-js/middleware/multipart",
        "arguments": [
          {
            "uploadDir": "/tmp/upload",
            "keepExtensions": true,
            "hash": "sha1",
            "multiples": false
          }
        ]
      }
    }
}

**Comment by jasisk** [comment]
The documentation is current but I see what happened here.

It may not be entirely clear but the format of the [Included Middleware](https://github.com/krakenjs/kraken-js#included-middleware) section does not reflect the format required for configuration—that section is merely intended to define which middleware ship with kraken and how they're configured by default.

The configuration format can be found in the [meddleware README](https://github.com/krakenjs/meddleware#options) (mentioned in the [middleware](https://github.com/krakenjs/kraken-js#included-middleware) section of the kraken readme):

> * module (_object_ **or** _string_) - The name or definition of the module to load containing the middleware implementation. Can be an installed module or a path to a module file within your project/application.

>   * name (_string_) - The name of the module or path to local module.

>   * method (_string_, optional) - The method on the provided module upon which invocation will create the middleware function to register. If a factory method is not provided, it defaults to the name of the current middleware being processed, and finally back to the module itself.

>   * arguments (_array_, optional) - An array of arguments to pass to the middleware factory.

Do you have any recommendation on how to better document that to make it more clear?

**Comment by berlincityboy** [comment]
Maybe examples how the actual json looks like would help.

By the way, do you know why I don't get my hash/checksum value generated with the posted multipart configuration?

**Comment by jasisk** [comment]
Closing as the original issue is resolved.
