### ISSUE TITLE
Configuration with confit module in separate different file as index.js

### ISSUE THREAD

**Issue by mickyloranger** [krakenjs/kraken-js#396]
Hi,
"I'm a newbie in JS"
I use nodemailer to send emails. To obtain a better stuctured code i decide to separate the creation of a transponder object in a diferent and i export this where it will required. To create a tranponder i must set some parameters loaded from a config.json. My question is: how to set this parameters in my transponder object when i create the object in a controller? Can i have a global access to an initialized 'confit' object?

This is easy when it's done in index.js as options for kranken object:

options = {
    onconfig: function (config, next) {
       db.config(config.get('databaseConfig'));
        next(null, config);
    }
};
app.use(kraken(options));

Thanks
Achille

**Comment by lmarkus** [comment]
See: http://krakenjs.com/#how-should-i-access-configuration-values-in-my-application
The configuration is available in the request object that your controller most likely receives: 

```javascript
function controller(req, res){
  var someConfigValue =   req.app.kraken.get('someConfigKey');
  res.send('The value is ' + someConfigValue);
}
```

**Comment by mickyloranger** [comment]
Thanks a lot.I didn't see that
