### ISSUE TITLE
sending localized strings via res.json

### ISSUE THREAD

**Issue by xShirase** [krakenjs/kraken-js#399]
Hi! 
My site is a one-page app, which means a lot of stuff happens via AJAX and res.json(). I have managed to use the locales for everything dust displays, but I was wondering what would be the best options to localize strings sent by the server via res.json(). 

I have a few ideas how I could proceed but I'd like to use what Kraken has to offer as much as possible instead of reinventing the wheel. How would you do it?

What I'm thinking would be a lib that reads the properties files when needed, based on the req locale but it seems to be potentially a lot of fs.read.

**Comment by aredridel** [comment]
Inside kraken, that's usually provided by bundalo -- either directly, or via makara 2's `makara.getBundler(req)`

**Comment by xShirase** [comment]
well, thanks a lot as usual, I was about to rewrite a bundalo module :smile:
