### ISSUE TITLE
http return status code ： - - ,why？

### ISSUE THREAD

**Issue by chelsh** [krakenjs/kraken-js#403]
![image](https://cloud.githubusercontent.com/assets/10752360/9056614/defe83f2-3ac6-11e5-9578-5f5ddae1b9fa.png)

**Comment by lmarkus** [comment]
What version of Kraken are you running?

**Comment by jasisk** [comment]
[Morgan] does this if there is no `res.statusCode`. There is no res.statusCode if [`res.writeHead` is used](https://nodejs.org/api/http.html#http_response_statuscode).

[Morgan]: https://github.com/expressjs/morgan/blob/b05e44aeeae8b7b15435057130a63401906b4f5f/index.js#L380

**Comment by chelsh** [comment]
version:

  "name": "kraken-js",
  "version": "1.0.3",
  "description": "An express-based Node.js web application bootstrapping module.",

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/9159422/17a5abf2-3f5b-11e5-993a-142a1271b5d9.png)

**Comment by chelsh** [comment]
"name": "express",
  "description": "Fast, unopinionated, minimalist web framework",
  "version": "4.12.3",

**Comment by chelsh** [comment]
response timeout , it must return statusCode:408,do not return ”－－“

**Comment by jasisk** [comment]
408 is for a client timeout. That is when the client (e.g., a browser), doesn't finish sending the request within a certain timeout (as defined on the server). What you're likely seeing is a _server_ timeout. That is when the client has completed the request, but the server has not responded within a certain timeout (as defined on the client). As the server, we cannot send a timeout response when it is the client that is determining the criteria of what is and is not a timeout.

It's a challenge to say why you're seeing this without viewing your app code but it appears you're either not actually sending a response for that request or—if you are sending a response—the thing facilitating that response is utilizing `response.writeHead`.

Either way, this is not a kraken issue so I'm closing however feel free to continue the discussion if you have any more questions.
