### ISSUE TITLE
how to set the value of request timeout?   parameter:"shutdown"?

### ISSUE THREAD

**Issue by chelsh** [krakenjs/kraken-js#404]
"shutdown" - internal middleware which handles graceful shutdowns in production environments
Priority - 0
Enabled - true if not in a development environment
Module - "kraken-js/middleware/shutdown"
Arguments (Array)
Object
"timeout" - milliseconds (default: 30000)

**Comment by jasisk** [comment]
The `timeout` property in shutdown has to do with graceful / forceful shutdowns of kraken. You can find more info on it in the [README](https://github.com/krakenjs/kraken-js#included-middleware).

kraken doesn't setup any `req`/`res` timeouts for you. That is not to say they won't timeout—inactive sockets will timeout after two minutes and any destroyed sockets are cleaned up—there is just no active socket timeout by default.

That said, if you want to implement one, you can use [connect-timeout](https://github.com/expressjs/timeout) to handle response timeouts (503).

I've not found a tidy module for request timeouts (408), however I believe you could accomplish this by setting up a timeout to respond with a 408, and clearing the timeout using the [on-finished](https://github.com/jshttp/on-finished) module with your `req` object. There may need to be some additional cleanup performed, but that should get you started.
