### ISSUE TITLE
Cannot find module 'engine-munger/lib/expressView'

### ISSUE THREAD

**Issue by joeblau** [krakenjs/kraken-js#406]
If you try and install engine-munger via `npm install`, the lib directory doesn't get created.

**Steps to reproduce:**
Use Kraken to create a standard application.
```bash
$ yo kraken

     ,'""`.
    / _  _ \
    |(@)(@)|   Release the Kraken!
    )  __  (
   /,'))((`.\
  (( ((  )) ))
   `\ `)(' /'

Tell me a bit about your application:

? Name: testkraken
? Description: test kraken
? Author: joe
? Template library? Dust
? Include i18n support? Yes
? Front end package manager ? Bower
? CSS preprocessor library? LESS
? JavaScript library? RequireJS
```

Then, remove the node modules directory and reinstall it and the application breaks.

```bash

$ rm -rf node_modules/
$ npm install
$ npm start

> testkraken@0.1.0 start /Users/joeblau/Developer/trash/testkraken
> node server.js

Server listening on http://localhost:8000
Possibly unhandled Error: Cannot find module 'engine-munger/lib/expressView'
```

**Comment by jasisk** [comment]
Hi Joe. Which version of the generator are you using?

**Comment by jasisk** [comment]
I tried locally and cannot seem to reproduce.
With the latest version of the generator (2.1.0), using the same settings as above (Dust, i18n, Bower, LESS, and RequireJS), the package requires [engine-munger@^0.2.5](https://github.com/krakenjs/generator-kraken/blob/2742512c5fbe5dc2696ea8ac69a552bd20c477df/app/dependencies.js#L31) (which presently resolves to v0.2.8). That version still has [./lib/expressView.js](https://github.com/krakenjs/engine-munger/blob/v0.2.8/lib/expressView.js).

Is it possible that you've installed engine-munger@^1.0.0? engine-munger went through a pretty extensive rewrite recently and, [starting with v1.0.0](https://github.com/krakenjs/engine-munger/tree/v1.0.0), that view shim went away.

**Comment by joeblau** [comment]
Ah yeah, I did install 1.0.0!  I'll switch my dependency and try again.

**Comment by jasisk** [comment]
The beauty of semver! :grinning:

Let me know how it shakes out.

**Comment by joeblau** [comment]
:+1: It worked! Open and shut case.  Thanks for your prompt feedback.

**Comment by jasisk** [comment]
The best kind of case—except, maybe, for a [Crave Case](http://www.whitecastle.com/food/menu/Big-Craves/crave-case) (side note: 4190 calories?!).

Best of luck with whatever project you're starting. :grinning:

**Comment by joeblau** [comment]
Hehe [my project](https://github.com/joeblau/gitignore.io) has been running on Kraken for about a year now and I get about 24k monthly uniques so having the site crash would make a few people unhappy.

**Comment by jasisk** [comment]
Ah. My mistake. I assumed you were working on something new with the generator.

in that case, I hope you have continued, uncrashing success! :grinning:
