### ISSUE TITLE
Using KrakenJS for microservices? Security and CSRF

### ISSUE THREAD

**Issue by joshbedo** [krakenjs/kraken-js#407]
I've been thinking about trying to set this up for one of my personal projects but i had a few concerns i wanted to ask others who probably have more experience. One of the main concerns is CSRF and the security module overall, would it be possible to have ServiceA and ServiceB work together with CSRF enabled? My guess was no thinking that the accepted CSRF codes on each server would differentiate.Also another concern was login sessions with Passport.Hopefully someone jumps in and tells me it is possible though :)  I want to explore creating docker images for each service and using krakenjs for the application tier.

Thanks!

**Comment by aredridel** [comment]
Sounds like CSRF attacks shouldn't be a concern, if browsers aren't talking to the services directly and there's an application tier in front.

**Comment by jasisk** [comment]
What Aria said.

It's worth point out, however, that both of the things you mentioned (csrf and auth) stem from the same root concern: shared session. csrf protection, for example, generally stores a token secret in the session (which is how tokens can be validated/invalidated between requests).

You're generally going to store your user state in the session—if each of your services access the same session, it does't matter which service you hit as they'll all share the same user context.

Look into using a different type of session store. Something like [redis](https://github.com/tj/connect-redis) for example.

**Comment by jasisk** [comment]
Closing out due to inactivity. Feel free to continue the conversation if necessary.

**Comment by joshbedo** [comment]
Sorry, i got this working by doing exactly what you said, i used redis as a shared session store and rabbitmq as a message bus. Thanks!
