### ISSUE TITLE
Problems with the sessions and HAProxy in OpenShift

### ISSUE THREAD

**Issue by rodmoreno** [krakenjs/kraken-js#411]
I have written an application using Kraken and deploy in OpenShift with the option of auto-scaling (use HAProxy) but this has led me two problems:

1) HAProxy constantly sends requests to the application, this resulted in a week has ~485k sessions stored in my redis.
2) Because of the constant requests HAProxy every time I try to see my log (using: RHC taill myapp) my logger shows a lot of these requests are useless to me.

Is there any way to fix this

**Comment by jasisk** [comment]
Closing as unrelated to kraken.

That said, sounds like your haproxy config needs some work. See the haproxy blog post titled, "[load balancing, affinity, persistence, sticky sessions: what you need to know](http://blog.haproxy.com/2012/03/29/load-balancing-affinity-persistence-sticky-sessions-what-you-need-to-know/)"—specifically the _using application session cookie for persistence_ section. Note that the default session cookie name for express is `connect.sid`.
