### ISSUE TITLE
What is the easiest way to mock dependencies of a controller?

### ISSUE THREAD

**Issue by konradjurk** [krakenjs/kraken-js#412]
Hey,

what would be the easiest way to use something like https://github.com/felixge/node-sandboxed-module to mock some dependencies of a controller for unit-testing purposes?

I think https://github.com/krakenjs/kraken-js/wiki/Using-kraken-js-middleware-config-to-setup-environment-specific-routes describes how to manually setup routes, but everything works with these JSON configurations so I can't use sandboxed-module.

Any ideas? :)

**Comment by lmarkus** [comment]
For unit testing, I like to keep the handler implementation separate from my routes.
eg: `routes/index.js`
```javascript
var somePathHandler = require('/controllers/somePath').handler;

module.exports =function(router){
    router.get('/somePath', somePathHandler);
}
```
`controllers/somePathHandler.js`:
```javascript
var dependencyCheck = require('dependency').someCheckFunction;

module.exports.handler = function (req, res){
    if( dependencyCheck() === 1){
        res.send('foo');
    }
    else {
        res.send('bar');
    }
}
```

(Assuming mocha), I personally like to use [sinon](http://sinonjs.org/), but there are many ways to solve this problem. In this example, I manipulate the required `dependency`, stubbing its `someCheckFunction` so I can specify what value it should return. By doing this, I can test both logic branches in my controller (returns `foo` or `bar`) and achieve 100% code coverage. 

`/test/controllers/somePathHandler.js`
```javascript
var sinon = require('sinon'),
    somePathHandler = require('../controllers/somePathHandler'),
    dependency = require('dependency');

describe('somePath tests'){

    /* Setup and teardown of dependency mock */
    var someCheckFunctionStub;
    beforeEach(){
        someCheckFunctionStub = sinon.stub(dependency, 'someCheckFunction')
    }

    afterEach(){
        someCheckFunctionStub.restore();
    }

    /*Actual tests */
    it('returns foo when someCheckFunction is 1',function(){
        someCheckFunctionStub.returns(1); // Force the mock function to return 1
        var req = {},
            res = {send:function(value){assert(value ===  'foo');}};
        somePathHandler.handler(req, res);
    });

    it('returns bar when someCheckFunction is  different from 1',function(){
        someCheckFunctionStub.returns(0); // Force the mock function to return 0
        var req = {},
            res = {send:function(value){assert(value ===  'bar');}};
        somePathHandler.handler(req, res);
    });
}
```

**Comment by grawk** [comment]
answered
