### ISSUE TITLE
how to debug the dust file?

### ISSUE THREAD

**Issue by chelsh** [krakenjs/kraken-js#413]
`res.render('1.6/topic',{topic:resultObj});`

----how to debug the topic.dust?

**Comment by aredridel** [comment]
try looking at the compiled JS. You can un-minify it with `uglifyjs -b`. It's not easy -- all the helpers are `h`, lots of short names.  Use dustc, and use the `js` engine if you need to step through it.

**Comment by chelsh** [comment]
i use kraken-js framework,when render the dust file,happen error,but the error info is not  be detailed:
![image](https://cloud.githubusercontent.com/assets/10752360/9840647/ef620c84-5ac7-11e5-9a3f-1079aec7ae4c.png)


---can i set the config to make the error info be detailed?

**Comment by aredridel** [comment]
No. The error you're getting is a syntax error in your dust template, which the parser in dustjs is ... not that useful giving good info.

You may want to try running dustc on the template though, and see if it gives you any more context.
