### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by Vorror** [krakenjs/kraken-js#414]
It seems the last "real" non-merge commit was April 23, 2015. I'm looking at the [dep state](https://david-dm.org/krakenjs/kraken-js#info=dependencies&view=table)  and there seems to be a quite a bit of outdated dependencies + a security issue. It seems Kraken is also out of date on it's own module(meddleware)? I guess you could make the argument that 2.0 is up to date with meddleware but 2.0 also doesn't seem to be in active dev either. I would just like to know if Kraken is still in active/public development?

I also think adding the dependency badge would be a nice touch :)

**Comment by lmarkus** [comment]
Yes, it's very much alive and well.
The team manages versions by branches. The default being 1.x, which doesn't see too much activity anymore.
Check out https://github.com/krakenjs/kraken-js/commits/v2.x though.

Also, Kraken (the framework) is really the aggregate of a lot of smaller sub-modules which are also very much in active development. 

Look at the overall activity and latest update dates in the organization as a whole: https://github.com/krakenjs

**Comment by Vorror** [comment]
Great! Thanks! :)

**Comment by jasisk** [comment]
Yup. Like Lenny said.

We're in a weird spot with kraken. We sit on top of express so framework level concerns are captured there. We also orchestrate our other modules which, as @lmarkus pointed out, have seen more activity.

We are currently evaluating some other, kraken-level changes but, regardless, still very active. :)

**Comment by tlivings** [comment]
On this note we should probably update our default branch soon :)

**Comment by strongSoda** [comment]
still active?
