### ISSUE TITLE
Update license to post-split language

### ISSUE THREAD

**Issue by Vorror** [krakenjs/kraken-js#415]
I would assume Paypal owns the license, but in the license.txt and all throughout the code I see "Copyright (C) 2014 eBay Software Foundation". Is it Paypal or eBay that owns the license to code? I can't seem to find any press regarding eBay's contribution to Kraken.

**Comment by Vorror** [comment]
Forgot ebay/paypal split ;)

**Comment by jasisk** [comment]
Good call though. We should update that to current language. I'm reopening and changing the subject to make sure this is captured.

**Comment by shaunwarman** [comment]
Bump

**Comment by gabrielcsapo** [comment]
fixed in https://github.com/krakenjs/kraken-js/commit/3899819983ca16b6e5509826ffaca2a1e5f0bd7a
