### ISSUE TITLE
Static Files and req.url

### ISSUE THREAD

**Issue by tomalex0** [krakenjs/kraken-js#416]
I would like to verify one behavior i was  looking in to
Below is  part of `config.json` and i'm writing a  `middleware`  for all routes when i `console .log(req.url)`  i don't see  static css and js in `req.url`.

```
"static": {
            "module": {
                "arguments": [ "path:./public" ]
            }
        },
"custommiddle": {
            "enabled": true,
            "priority": 150,
            "module": {
                "name": "path:./lib/custommiddle"
            }
        }
```

I tried with normal express app with `app.use` and i could see all css and js request in `req.url`
```
app.use(express.static(__dirname + '/public'));
```

**Comment by jasisk** [comment]
You have your custom middleware at priority 150. Kraken ships with the [static middleware at priority 40](https://github.com/krakenjs/kraken-js/blob/64f764160ee8491141960fc7755fdf05e7ae6776/config/config.json#L43-L50) and the [default router at priority 120](https://github.com/krakenjs/kraken-js/blob/64f764160ee8491141960fc7755fdf05e7ae6776/config/config.json#L133-L144).

So will do what you want:
``` js
{
  "middleware": {
    "custommiddle": {
      "enabled": true,
      "priority": 39,
      "module": "path:./lib/custommiddle"
    }
  }
}
```
