### ISSUE TITLE
Kraken option for loading middlewares after default middlewares

### ISSUE THREAD

**Issue by jadengore** [krakenjs/kraken-js#418]
I have a middleware function that depends on `req.params` being parsed (the route parameters), and I've been unable to access this value. I tried custom-loading the middleware in `onConfig`, but from what I can tell this occurs before loading default middlewares such as `body-parser`.

I tried attaching the middleware after `app.use(kraken(options))` to no avail as well. Where should middleware that depends on Kraken's default middleware be initialized?

**Comment by jasisk** [comment]
Check out the documentation on [middleware](https://github.com/krakenjs/kraken-js#middleware):
> Much like configuration, you shouldn't need to write a lot of code to determine what's in your middleware chain. [meddleware] is used internally to read, resolve, and register middleware with your express application. You can either specify the middleware in your `config.json` or `{environment}.json`, (or) import it from a separate json file using the import protocol mentioned above.

In other words, you register your middleware in your config. As mentioned, we use [meddleware] to facilitate this so definitely check out that repo for the full API.

As an example, say you've written a custom middleware and placed it in `./lib/myCustomMiddleware`:
``` js
module.exports = function createMyCustomMiddleware() {
  // note that you export a function that _returns_ your middleware!
  return function myCustomMiddleware(req, res, next) {
    // ... do custom middleware stuff ...
    next();
  };
};
```

I could include that in my kraken app by adding the following in the appropriate part of my config:
``` js
{
  // ... snip ...
  "middleware": {
    // ... snip ...
    "myCustomMiddleware": {
      "enabled": true, // make sure to enable it
      "priority": 119, // set the priority appropriately
      "module": {
        "name": "path:./lib/myCustomMiddleware"
      }
    }
  }
}
```

I set the priority to 119 because that's _just_ before the default `router` (as documented in the [Included Middlewares](https://github.com/krakenjs/kraken-js#included-middleware) section of the kraken README).

[meddleware]: https://github.com/krakenjs/meddleware

**Comment by jadengore** [comment]
So I just tired implementing this, and `req.params` is still `{}`. `body-parser` is included in Kraken right?

**Comment by jasisk** [comment]
[Yup](https://github.com/krakenjs/kraken-js/blob/64f764160ee8491141960fc7755fdf05e7ae6776/config/config.json#L61-L84).

**Comment by jasisk** [comment]
So a couple of things:
1. If you're registering middleware outside of kraken's config, that's a problem. when you `app.use(kraken())`, a bunch of stuff resolve async, so middlewares you include with subsequent `app.use` calls will actually end up _before_ kraken.
2. Are you using sub-applications? If so, are you aware of the [mergeParams](http://expressjs.com/4x/api.html#router) option on your routers?

**Comment by jadengore** [comment]
1. Most of the middleware used in my application requires async, which is why I had been initializing this middleware in `onConfig`. I had read the middleware documentation, but when you linked it again in this thread it instantly clicked and I realized why the middleware I'm currently working on needs to be in the `config.json`.

2. No sub-apps. What I meant by sub-routers was actually router middleware, such as validation, database requests, etc. In the express router middleware, I do have access to `req.params`, but I still am unable to access these.

**Comment by jasisk** [comment]
Any update on this issue? Still a problem?

**Comment by jadengore** [comment]
@jasisk Thanks for pinging, I think this can be closed. It's mainly a problem of this middleware needing to be loaded at the controller-level, so that I have access to `req.params`. Since Express won't parse this until the router has loaded, it is easier to load this middleware where needed in my Express app itself.

**Comment by jasisk** [comment]
Sounds good. Glad you found a solution that works for you. :grinning:
