### ISSUE TITLE
Reading Dust templates outside of req,res

### ISSUE THREAD

**Issue by xShirase** [krakenjs/kraken-js#421]
I'm trying to render localized emails in my Kraken app.
I used to use bundalo and it worked fine as long as my email was short enough. But we're growing more complicated and so are our templates so I'm trying to switch to rendering dust templates.

The templates are created, localized and compiled (in production mode).
In my model, I use : 

````
emailLib.sendConfirmation({login:req.body.email,code:code}, res.locals.context, function(err,ret){
       if(err){
            res.status(200).json({});
       }else{
            res.status(200).json({});
       }
});
````

Then, in /lib/email.js, I try :
````
sendConfirmation: function(user,locale,cb) {
     adaro.render('emails/welcome', { login: user.login, confirmationURL: user.code }, function(err, out) {
            if(err){
                  console.log('err: ',err);
            }else{
                  console.log(out);
            }
       });
````

And I get a TypeError: undef is not a function.

So, first of all, I'm not sure if adaro already has the locale configured (in my mind, it should but I'm probably wrong). But I don't think the issue is there as it would simply fallback to en/US.

My idea was that adaro was global and would be enough for me to load the template from the concatenated localized files, like in req,res methods. I'd like to avoid fs.readFile to read the template each time I need it, any clue?

**Comment by aredridel** [comment]
Which version of adaro?

Adaro 1.0 should let dust cache the templates, so a loader that uses fs.readFile should be fine, as it will only be called for templates not in cache.

Which module are you using for internationalization"?

**Comment by xShirase** [comment]
All the strings are in locales/**/.properties, then I grunt build my templates into concatenated files (1 per locale).
Then I use localeresolver to figure out a user's locale.

For the email specifically, I used the locale passed to the function to pass to bundalo and get the relevant strings. However, a 200lines HTML email doesn't really qualify as 'string' and I ran into all sorts of trouble with special characters.

It appears that I have adaro 0.1.10, so I'll try updating before anything, thanks!

**Comment by aredridel** [comment]
Aah, the old way! 

Yes, that's much more complicated to get right. It doesn't play well with caching, because template name to file name is not mapped 1:1. The new adaro handles language separate from template, with dust-makara-helpers, and you can just use the dust cache straightforwardly, and there's no per-locale template build. Just one single template compile.

**Comment by xShirase** [comment]
alright, now :
````
 npm info adaro version
1.0.0
````

But still the same thing. Would you have an example of the 'new way'? I didn't realize how fast time has passed since I started this project!

**Comment by aredridel** [comment]
You'll want to look at http://krakenjs.com/2015/07/06/new-i18n-for-dust.html and I really should put together a simple demo of using adaro without kraken, but haven't done so yet. Happy to give advice if you want to make a small model of what you're doing in a repo.

**Comment by xShirase** [comment]
I can try to cut this part out of my main project and make it a simple demo. Thanks again for your help, you're the only person I was sure to get an answer from on a sunday night! I'll link you to the demo repo after I read the new stuff.

**Comment by xShirase** [comment]
Ok, what do you think is the minimal setup for a demo of i18n outside kraken?
The most frequent use case (and mine) is to generate emails, I've seen the question a few times already, so I'm up for that, but if you think there's something better, I'd go for it and adapt my own project later. Time to give back to the community!

New repo created : https://github.com/xShirase/adaro-noKraken-example

**Comment by xShirase** [comment]
btw, lets move discussion to the new repo so it's easier to follow

**Comment by aredridel** [comment]
:+1:
