### ISSUE TITLE
Error message templates

### ISSUE THREAD

**Issue by rhettl** [krakenjs/kraken-js#423]
Hello, 

I have been trying to work with error messages for the last couple days. I cannot seem to get the HTML/Dust templated output I am expecting. I am using the standard `404.dust`, `500.dust` and `503.dust` located in `./public/templates/errors/` generated by `npm i generator-kraken -g && yo kraken`, but I am only getting plain text error messages.

For example, if I go to `/someRandomPage` expecting a `404` response with `h1` and `p`:
```dust
{>"layouts/master" /}

{<body}
    <h1>{@pre type="content" key="header"/}</h1>
    <p>{@pre type="content" key="description"/}</p>
{/body}
```
I only get plain text `Cannot GET /someRandomPage`

this is the same for dev and production environments.

I have tried to read up on how the error messages middleware is working, but I cannot find any information on it in these issue files or on the kraken website. I assume there is something I am doing wrong, but I just cannot see it.

**Comment by rhettl** [comment]
I have also tried following express best practices of adding this to my index.js to catch any errors:
```javascript
app.use(function errorHandler(err, req, res, next) {
  console.log('Test', err);
  if (err) {
    // Code here
  } else {
    next();
  }
});
```

but `console.log('Test', err)` never gets called. I've tried placing this in multiple places, including just after `app = module.exports = express();` and just after `app.use(kraken(options));`

**Comment by jasisk** [comment]
Hey @rhettl,

You're not doing anything wrong—we were just a bit overzealous about deprecating a feature. My apologies.

The reason it's not working the way you want it to is because the custom 404 and 500 middleware aren't configured by default anymore.

To get them working again, add these two blocks inside your config's `middleware` section:
``` js
{
  "middleware": {
    // ... SNIP ...

    "notfound": {
      "enabled": true,
      "priority": 125, // anything after the default router which is priority 120
      "module": {
        "name": "kraken-js/middleware/404",
        "arguments": [ "errors/404" ]
      }
    }

    "errorhandler": {
      "enabled": true,
      "priority": 130, // generally should be the last thing so, in this case, anything after 125
      "module": {
        "name": "kraken-js/middleware/500",
        "arguments": [ "errors/500" ]
      }
    }

    // ... SNIP ...
  }
}
```

Let me know how that works out for you.

**Comment by jasisk** [comment]
As for _why_ they're not configured anymore:

The default error handler in express is generally sufficient for development and it's otherwise totally transparent.

By including automatically preconfigured middleware for error handling, we found a lot of developers were confused as to how errors were being captured. This led to massive confusion when the first thing they'd do after generating a new app is ripping out the rendering engine—something the error handling (with templates!) assumed would exist.

No doubt this is a documentation shortcoming on our part so thanks for pointing that out.

**Comment by rhettl** [comment]
Alright, so I understand the reasoning behind the change and I can see the connections which are happening, but the changes you provided aren't making any changes. I read what you provided and it all makes sense what it should be doing:
- `priority` `125` and `130` are setting these modules to run after all other normal operations. 
- `module`.`name` is referring to `./node_modules/kraken-js/middleware/404.js` and is just taking the function in the exports and calling it with the argument set, in this case the template we care about, `.build/templates/errors/500.js`

and for custom error codes I could make `./lib/customError.js` (which would look identical almost to `500.js`), and `./public/templates/errors/customError.dust` and use something like 
```javascript
"customError": {
      "enabled": true,
      "priority": 129,
      "module": {
        "name": "./lib/customError",
        "arguments": [ "errors/customError" ]
      }
    }
```

Also, does the name of the middleware matter? for example `notfound` or `errorhandler` or `customError`? or are they just text for clearer human understanding?


Here is my `./config/config.json` for reference:
```json
{
  "express": {
    "view cache": false,
    "view engine": "js",
    "views": "path:./.build/templates"
  },
  "view engines": {
    "js": {
      "module": "makara",
      "renderer": {
        "method": "js",
        "arguments": [
          {
            "cache": true,
            "helpers": "config:dust.helpers"
          }
        ]
      }
    }
  },
  "dust": {
    "helpers": [
      "dust-makara-helpers",
      "./lib/dust-helpers"
    ]
  },
  "i18n": {
    "contentPath": "path:./locales",
    "fallback": "en-US"
  },
  "specialization": {
  },
  "middleware": {
    "makara": {
      "priority": 100,
      "enabled": true,
      "module": {
        "name": "makara",
        "arguments": [
          {
            "i18n": "config:i18n",
            "specialization": "config:specialization"
          }
        ]
      }
    },
    "static": {
      "module": {
        "arguments": [
          "path:./.build"
        ]
      }
    },
    "router": {
      "module": {
        "arguments": [
          {
            "directory": "path:./controllers"
          }
        ]
      }
    },
    "appsec": {
      "module": {
        "arguments": [
          {
            "xframe": "SAMEORIGIN",
            "p3p": true,
            "csp": true
          }
        ]
      }
    },
    "csrf": {
      "enabled": true,
      "priority": 111,
      "route": "/((?!days))*",
      "module": {
        "name": "lusca",
        "method": "csrf",
        "arguments": [
          {}
        ]
      },
      "notfound": {
        "enabled": true,
        "priority": 125, 
        "module": {
          "name": "kraken-js/middleware/404",
          "arguments": [ "errors/404" ]
        }
      },
      "errorhandler": {
        "enabled": true,
        "priority": 130, 
        "module": {
          "name": "kraken-js/middleware/500",
          "arguments": [ "errors/500" ]
        }
      }
    }
  }
}
```

**Comment by jasisk** [comment]
You've stuck the two middleware at the wrong level. They're nested inside `csrf`, not `middleware`.

**Comment by jasisk** [comment]
> Also, does the name of the middleware matter? for example notfound or errorhandler or customError? or are they just text for clearer human understanding?

They're generally for human consumption though they're also used as keys and 1) must be unique and 2) cannot contain a dash.

Also, for what it's worth, you don't need to have a separate `csrf` section.[ `appsec` is what is configuring lusca](https://github.com/krakenjs/kraken-js/blob/64f764160ee8491141960fc7755fdf05e7ae6776/config/config.json#L117-L131), so you can just throw a `"csrf": true` inside your `appsec` `arguments` array and get rid of the `csrf` middleware section.

**Comment by rhettl** [comment]
Thank you for catching that. That is an embarrassing mistake, but anyone could have made it I guess, hehe.

As for the CSRF change, I'm following the guide on [krakenjs.com/#faq](http://krakenjs.com/#faq) for disabling CSRF on my `/days` route. I have a post there on which I don't want CSRF, but I do want it on the all the main pages.

**Comment by jasisk** [comment]
Hah. No worries. When I don't make a nesting error, it's a successful day. :grinning:

Re: csrf, my mistake. You're absolutely correct. I glazed over the `route`.
