### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by waltergms** [krakenjs/kraken-js#424]
Hi!
I'm having trouble getting the translation in a particular view, my question is this, if I set the fallback in key config.json file i18n, cant i render a view using another language?
Eg,.:
*\* In my index controller **

```
router.get('/', function (req, res) {
    res.locals.context = { locality: { language: 'pt', country: 'BR' } };        
    res.render('index', model);
});
```

*\* In my config.json **

```
    "i18n": {
        "contentPath": "path:./locales",
        "fallback": "en-US"
    },
```

this should be rendering my pt-BR template, but is rendering the en-US

**Comment by grawk** [comment]
Assuming your application is generated with the "makara2" option from generator-kraken and further assuming your makara middleware is taking the `i18n` config yes it should work. Can you share your package.json dependencies section so I can remove some of these assumptions?

**Comment by waltergms** [comment]
```
"dependencies": {
    "construx": "^1.0.0",
    "construx-copier": "^1.0.0",
    "construx-dustjs": "^1.1.0",
    "construx-less": "^1.0.0",
    "dust-makara-helpers": "^4.1.2",
    "express": "^4.12.2",
    "kraken-js": "^1.0.3",
    "makara": "^2.0.3"
  },
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-browserify": "^3.8.0",
    "grunt-cli": "^0.1.13",
    "grunt-config-dir": "^0.3.2",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-jshint": "^0.10.0",
    "grunt-contrib-less": "^1.0.1",
    "grunt-copy-to": "0.0.10",
    "grunt-dustjs": "^1.2.1",
    "grunt-makara-browserify": "^1.0.1",
    "grunt-mocha-cli": "^1.14.0",
    "mocha": "^1.18.0",
    "supertest": "^0.9.0"
  }
}
```

**Comment by grawk** [comment]
Ah ok. You have chosen the browserify option. Let me try that locally. I had generated an app with the requirejs option where I had no problem loading different locales.

**Comment by grawk** [comment]
I am able to reproduce the issue. I won't be able to debug it further right now but should be able to look over the weekend.

**Comment by grawk** [comment]
In your controller, simply set `res.locals.locale` as opposed to `res.locals.context.locality` e.g.

```
res.locals.locale = { language: 'pt', country: 'BR' };
```

engine-munger will pick this up here:
https://github.com/krakenjs/engine-munger/blob/v1.x/index.js#L108

I've been trying to figure out where you saw it documented (or used) to set `res.locals.context.locality` but I couldn't find the source of that. Can you let me know where you found it @waltergms?
