### ISSUE TITLE
question about the current state of KrakenJS

### ISSUE THREAD

**Issue by ygrenzinger** [krakenjs/kraken-js#432]
Hello,

It's more a question than an "issue".

I have finished a website more than one year ago with KrakenJS 1.x and I want to rethink it to make a better version (using postgres instead of mongodb and maybe react instead of dustjs).

I hope to stay with KrakenJS which brings some good structure and lib on top of express.

However I am a bit lost by the difference between the examples and the KrakenJS generator which don't use the same libs (construx for example).

What is your advice ? Is the generator the correct way ? do you have up to date example ?

**Comment by aredridel** [comment]
Generator will get you started, but there's no harm in doing it yourself.

construx is kraken-devtools renamed; it's not a huge change. Most of the changes in kraken 2 are incremental.

**Comment by ygrenzinger** [comment]
Hello Aria,

Always on board :+1: 

Thanks a lot for the answer. Hope to find a way to work on this second version and help you to improve KrakenJS :)

**Comment by jasisk** [comment]
> Most of the changes in kraken 2 are incremental.

Precisely. The differences are mostly around refactors. The version bumps due to some different edge-cases. `construx` is `devtools` refactored into a set of independent modules ([see all the split out modules here](https://github.com/krakenjs?utf8=✓&query=construx)). Regarding the changes from kraken v1 to kraken v2, [check out the release notes](https://github.com/krakenjs/kraken-js/releases/tag/v2.0.0).

You could just bump kraken to 2 and go from there or start from scratch. Either way, you'll likely end up in just about the same place. :grinning:

**Comment by ygrenzinger** [comment]
First try is sadly not so successful. Dust helpers like @eq doesn't work as before.
But I think there is too moving part to clearly understand where does the problem comes from.

**Comment by grawk** [comment]
Going back to your core question about a ReactJS example, that's an excellent idea. We may not have one published yet. But I'm pretty sure there is one in progress.

Was there a specific path through the generator that led you to generated dust with the `@eq` helper?

**Comment by mikesparr** [comment]
+1 for ReactJS example and would REALLY like to see with MaterialUI. Was considering Meteor + MaterialUI but still love KrakenJS' enterprise architecture and i18n. Nearly a year since this thread so I'm curious if any movement on ReactJS yet? Thx!

**Comment by grawk** [comment]
There is a ReactJS example which uses react-router, client/server rendering:
https://github.com/krakenjs/kraken-example-with-shoppingcart

We have been namespacing our react-specific modules as `anemone`. 

As of yet a react flavor isn't baked into the generator though that might be something we can do shortly.

**Comment by grawk** [comment]
the generator now uses construx modules. otherwise, answered.
