### ISSUE TITLE
Support for Unix Domain Sockets

### ISSUE THREAD

**Issue by vhmth** [krakenjs/kraken-js#433]
We run routes tests at my current employer by spinning up a Kraken server and using superagent to make requests against it. Unfortunately, if the server is listening on a specified port and there are multiple people running the tests on our development machines (which we SSH into), we run into the `EADDRINUSE` issue. Are there plans for configuration-driven unix domain socket support for Kraken?

**Comment by lmarkus** [comment]
Kraken is just a layer on top of express.
If you can do it in express, you can do it in Kraken.

Does something like this help?
http://www.reapingzombies4funandprofit.com/blog/archives/52

**Comment by jasisk** [comment]
``` js
var kraken = require('kraken-js');
var express = require('express');
var app = express();

app.use(kraken());

app.on('start', function () {
  app.listen(app.kraken.get('PORT'), function () {
    var address = this.address().port || this.address();
    console.log('listening on %s ...', address);
  });
});
```

With the above, you can specify the `port` (or, [since the method signature for a socket is the same](https://nodejs.org/api/http.html#http_server_listen_path_callback), the `path`) by configuring `PORT` through any means supported by [confit](https://github.com/krakenjs/confit) such as the `config.json`, a command line argument, etc.

For example: `node server.js --PORT "/tmp/kraken-000.sock"`

**Comment by vhmth** [comment]
Thanks so much guys! In retrospect this seems so obvious. I guess I was really tired. :-P

With the ephemeral port, my fear is that it still leaves room for collisions - albeit the chance is so low that this is the correct practical approach.

Thank you guys!

**Comment by aredridel** [comment]
No collision possible with proper ephemeral ports since they're assigned by the operating system.

**Comment by vhmth** [comment]
Back to :school: session for me. Reading into ephemeral ports now. Thank you @aredridel.
