### ISSUE TITLE
Error: cannot find module 'latest-version' (RESOLVED)

### ISSUE THREAD

**Issue by quarterpi** [krakenjs/kraken-js#442]
Ok, I figured it out. It was a permissions issue. I didn't catch it right away because the krakenjs website says to run the install command with sudo, which I wouldn't recommend. If anyone else encounters this problem, try running the instal command without sudo. If you get EACCES error, try following the instructions on npm's website. https://docs.npmjs.com/getting-started/fixing-npm-permissions

------------------------------------------ RESOLVED -------------------------------------------------------------------------------
Hi, I'm new to Kraken so forgive me if this is not an error, or if it was my error. 
I just updated node to v5.3.0 and npm to v3.3.12, then installed kraken. While installing, generator-kraken complained that 'generator-kraken@2.1.2: wanted: {"npm":"^2.0.0"} (current: {"node":"5.3.0" , "npm":"3.3.12"}).
I then navigated to a test folder and tried to "summon the kraken" via ```yo kraken``` which failed with the error message "Error: cannot find module 'latest-version' at Function.Module_resolveFilename (module.js:326:15)".

I found what looked to me like a similar issue here https://github.com/sintaxi/harp/issues/462 where they suggested that their issue was *"because the new version of npm now has a flat structure for modules, relative paths referencing node_modules fail"* but I could be way off.

**Comment by jasisk** [comment]
Great! Thanks for the update.
