### ISSUE TITLE
require errors are no longer logged

### ISSUE THREAD

**Issue by lebretr** [krakenjs/kraken-js#444]
Hi,

I created a new kraken app  with the generator but the errors on a require are not longer logged.

After some tests, I think the problem is in express-enrouten (in /lib/directory.js file)
With v1.2.1 it' ok but with v1.2.2, i haven't  require error log

**Comment by jasisk** [comment]
> errors on a require

I'm not sure I follow. Are the "controller" files in a directory failing silently? Can you give me a little more info? A rep link or some demo could would help me understand a bit better.

**Comment by lebretr** [comment]
with express-enrouten@1.2.1, 
In a controller, if I require a no exist file (model, lib,...) or a file with error ( bad syntax,...), I have an error in my console and no routes are loaded.

with express-enrouten@1.2.2, 
In a controller, if I require a no exist file (model, lib,...) or a file with error ( bad syntax,...), I have No error in my console but others routes in others controller files are loaded.
Without error log, it is less easy to debug

**Comment by jasisk** [comment]
Ah. I see. You're absolutely right.

I made a change to express-enrouten with 1.2.2 to no error out on accidentally required files. As a side-effect, it _does_ eat require errors.

I've opened an issue in that repository—let's track it there (closing this one in favor of that):
https://github.com/krakenjs/express-enrouten/issues/79
