### ISSUE TITLE
Internationalisation with Jade template engine?

### ISSUE THREAD

**Issue by frenchbread** [krakenjs/kraken-js#445]
Is it possible to have a kraken app that uses Jade as a template engine and at the same time contains internationalisation?

**Comment by grawk** [comment]
Yes you should be able to do this. Are you thinking a single set of jade templates which would draw content from any of multiple locale directories? That would be analogous to all our current examples (which use dust).

You can use [bundalo](https://github.com/krakenjs/bundalo) to convert the locale-appropriate properties file into JSON which you can then put into the view model prior to `res.render`.

I don't have a lot of experience with Jade, but what I have is on the server-side. If you don't plan to render Jade templates on the client (not sure if anybody does that) then the above high-level approach should work.

I'd be happy to work with you on this.

**Comment by frenchbread** [comment]
> That would be analogous to all our current examples (which use dust).

Sounds cool, but the issue it that since syntax is a bit different, I am not really sure how to set up config files and grab i18n values inside `.jade` file. (not familiar with dust)

Could you note, what changes should I add to [`kraken-example-with-i18n`](https://github.com/krakenjs/kraken-example-with-i18n) in order to have it all set up?

**Comment by grawk** [comment]
I'd like to do that. But I probably can't do so terribly quickly. As a small tidbit in the meantime, we are using bundalo [here](https://github.com/krakenjs/kraken-example-with-shoppingcart/blob/master/controllers/cart/index.js#L22) to grab the correct locale content, and we include the content in the data model in `res.render`. It would be the same mechanism you'd want to use for Jade. Then in the template, you access the view model just as you always would.

**Comment by frenchbread** [comment]
Ah, I see. Thanks. I'll try it.
