### ISSUE TITLE
How to create dynamic controller by using command line  

### ISSUE THREAD

**Issue by realdog** [krakenjs/kraken-js#446]
I use the command line to create general controller
```
yo kraken:controller  controller_name/abc/index
```
But I dont know how to create a e dynamic controller by using command line,the dynamic controller like:

```
/command/:appid/:userid/some_fixed_key
```

**Comment by realdog** [comment]
I try the command
```
yo kraken:controller command/:appid/some_fixed_key
```
And it worked.....but...how to get the appid from the req.params( the value is null) .....i will try use regex to get appId...but is there any way to make it more elegant?

**Comment by jasisk** [comment]
Hey @realdog ( henceforth, :dog:),

In your route handler, you'll be able to access the param as a property on `req.params`. So, continuing your example, you'd check `req.params.appid`.

Check out the [express documentation's section on `req.params`](http://expressjs.com/en/4x/api.html#req.params) for more info.

**Comment by realdog** [comment]
@jasisk Thank u very much.But the req.params just fine with /get/:appi ......but not work for '/action/:appid/get/:username'...
