### ISSUE TITLE
All pages return 404 when using Express error handling

### ISSUE THREAD

**Issue by byronh** [krakenjs/kraken-js#447]
After seeing that the `404` and `500` modules are [being deprecated](https://github.com/krakenjs/kraken-js/issues/359), I tried to follow the suggested method of using Express's normal error handling.

The [Express FAQ](http://expressjs.com/en/starter/faq.html) says the following:

> All you need to do is add a middleware function at the very bottom of the stack (below all other functions) to handle a 404 response:
> 
> ``` javascript
> app.use(function(req, res, next) {
>   res.status(404).send('Sorry cant find that!');
> });
> ```

As expected, creating a Hello World app with just Express properly shows a 404 message for nonexistent routes and shows the working page at `localhost:3000/working`:

``` javascript
var app = require('express')();

app.use(require('kraken-js')());

app.get('/working', function(req, res) {
    res.send('Working page');
});

app.use(function(req, res, next) {
    res.status(404).send('404 page');
});

app.listen(3000);
```

However, creating a fresh Kraken project doing the same thing results in **all** routes returning 404s even if there are valid routes defined in the `controllers` folder:

``` javascript
var express = require('express');
var kraken = require('kraken-js');


var options, app;

/*
 * Create and configure application. Also exports application instance for use by tests.
 * See https://github.com/krakenjs/kraken-js#options for additional configuration options.
 */
options = {
    onconfig: function (config, next) {
        /*
         * Add any additional config setup or overrides here. `config` is an initialized
         * `confit` (https://github.com/krakenjs/confit/) configuration object.
         */
        next(null, config);
    }
};

app = module.exports = express();
app.use(kraken(options));
app.on('start', function () {
    console.log('Application ready to serve requests.');
    console.log('Environment: %s', app.kraken.get('env:env'));
});
app.use(function(req, res, next) {
    res.status(404).send('404 page');
});
```

Attempting to add the error handler to `onconfig` also results in all routes returning 404:

``` javascript
options = {
    onconfig: function (config, next) {
        /*
         * Add any additional config setup or overrides here. `config` is an initialized
         * `confit` (https://github.com/krakenjs/confit/) configuration object.
         */
        app.use(function(req, res, next) {
            res.status(404).send('404 page');
        });
        next(null, config);
    }
};
```

Is the only alternative to have duplicate error handlers in every single controller?

I also suggest that the proper method of error handling be documented in the readme, as it is currently very difficult to find up-to-date information on error handling in Kraken (especially for 500 errors).

**Comment by jasisk** [comment]
The problem is here is in the way you're registering your middleware. In a kraken app, you register your middleware in a config file. If you `app.use(something())` after you `app.use(kraken())`, your `something()` will actually occur *first* in the middleware chain (kraken does some async work).

In the case above, your 404 handler is handling _everything_, having been registered before the middleware configured by kraken. If you move it onto the config and let kraken register it, all will be resolved.

**Comment by kelthenoble** [comment]
:+1: nicely answered @jasisk

**Comment by byronh** [comment]
Good explanation, thanks! I recommend describing this a bit more explicitly in the readme because Kraken handles middleware entirely different than Express, so pointing users to the Express docs could be a bit confusing.

**Comment by lordKnighton** [comment]
cc @jasisk 

--

close issue please 😄
