### ISSUE TITLE
shutdown.js has possible strict violation

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [krakenjs/kraken-js#450]
```
function onceThunk() {
  var called = false;
  return function once(emitter, events, callback) {
    function call() {
      if (!called) {
        called = true;
// HERE: what does `this` mean here? We are just passing global scope here.
        return callback.apply(this, arguments);
      }
    }
    events.forEach(function (event) {
      emitter.once(event, call);
    });
  };
}
```

`npm run-script lint` throws this error.

**Comment by aredridel** [comment]
if `call` was called as a function, that would indeed be global scope; this preserves the `this` supplied by the event emitter, whatever it is. If that's global scope, that's fine. It keeps the existing semantics.

**Comment by IAmAnubhavSaini** [comment]
Interesting, didn't know that. 

What is the next course of action, linter throwing warnings is bad as it is. Should we add ignore warning?

**Comment by aredridel** [comment]
Yes, or disable that part of the linter. Linter is wrong.

**Comment by gabrielcsapo** [comment]
fixed in https://github.com/krakenjs/kraken-js/issues/449
