### ISSUE TITLE
Using Same config for subapps

### ISSUE THREAD

**Issue by tomalex0** [krakenjs/kraken-js#455]
My app comprises of multiple subapps which can be run in different port, similar to 
- https://github.com/jasisk/middleware-patterns/tree/master/sub/config
- https://github.com/jasisk/middleware-patterns/tree/master/config

I would like to point all subapps config to one folder rather than individual  subapp folder as config is same

I tried like this in all subapps `config.json`  but  it will not work as expected as i'm assigning to `config`

```
{
 config :  "import:../../../config/subapp-config.json"
}
```

What is the best option to accomplish this?

**Comment by tomalex0** [comment]
raised same in stackoverflow also http://stackoverflow.com/questions/36772092/using-same-config-for-subapps-krakenjs

**Comment by tomalex0** [comment]
Any help  is really appreciated.

**Comment by jonathansamines** [comment]
Hi @tomalex0 it is possible to you to load your sub-apps by using meddleware, and thus, pass each app configuration by using the meddleware module arguments? See: https://github.com/krakenjs/meddleware#options

**Comment by tomalex0** [comment]
@jonathansamines  subapp structure gives an option to run each as standalone app which runs in different port  and can take advantage of nginx to do the reverse proxy settings.

if you check https://github.com/jasisk/middleware-patterns/blob/master/package.json#L19 this will run subapp as standalone and read config from `sub` folder and if we have multiple sub apps, we will end up having config folder for those with config files.  Most probably all subapp will have similar config.  I'm looking for an option to point config folder to single one rather than looking into `sub` folder

**Comment by tomalex0** [comment]
This can be done with latest pull request 
https://github.com/krakenjs/kraken-js/pull/473

Not yet available in npm module.

**Comment by gabrielcsapo** [comment]
@tomalex0 we are pulling this in hopefully today, if nothing goes wrong with our integration tests 🤞

**Comment by gabrielcsapo** [comment]
published in https://github.com/krakenjs/kraken-js/releases/tag/2.2.0
