### ISSUE TITLE
default configuration JSON

### ISSUE THREAD

**Issue by vhmth** [krakenjs/kraken-js#457]
I noticed in [confit](https://github.com/krakenjs/confit/), you can define a defaults JSON file. Does this mean you can specify a `defaults.json` file (or something of that nature) and then Kraken will additionally loading `[config | staging | development].json` according to `NODE_ENV`? If that's the case, is there a path exposed to provide a `defaults.json` for Kraken to pick up on and extend from with the environment config? I find myself using a lot of the same configuration values across `staging`, `development` and `config`.

**Comment by jiangts** [comment]
if I'm not mistaken configs in `config.json` are applied across development, staging, and production environments.

**Comment by vhmth** [comment]
Oh man really!? I hope that's the case. It seems that way from the confit documentation, so if it is the case, maybe we should make it more explicit in the docs? Or change it to be `defaults.json`?

**Comment by jiangts** [comment]
I actually just started using kraken, but it definitely looks that way from what I've done so far...
Most of my configs go in `config.json` and overrides specific to different environments go in `__ENV__.json`.

And yeah, I'd say `defaults.json` is probably a better name as well...

**Comment by vhmth** [comment]
Yeah it's definitely the case looking at the source code (which is pretty readable):

https://github.com/krakenjs/confit/blob/2.x/lib/factory.js#L33

They try to load the default `config.json` and then resolve a `NODE_ENV` config after. Thanks @jiangts!

**Comment by vhmth** [comment]
I'll leave it to the discretion of a maintainer to close this or potentially make it so confit also looks for `defaults.json`.

**Comment by jasisk** [comment]
@jiangts is correct—a `config.json` is always used while an optional environment-specific config is overlaid on top.

The [documentation](https://github.com/krakenjs/kraken-js#environment-aware) could probably stand to be a bit more clear about this. Either of you want to give clarifying it a bit there a shot? I'll close this out and open a new issue to clean up the documentation.

Thanks for the report!
