### ISSUE TITLE
Contact information outdated

### ISSUE THREAD

**Issue by shaunwarman** [krakenjs/kraken-js#461]
Email information out of date post split in the [Contact Us](https://github.com/krakenjs/kraken-js/blob/v2.x/SECURITY.md#contact-us) section.

**Comment by lordKnighton** [comment]
CC @jasisk would you like me to submit a `PR` for this?

**Comment by grawk** [comment]
@lordKnighton PR welcome!

**Comment by grawk** [comment]
resolved with #476
