### ISSUE TITLE
Use internationalization on server side

### ISSUE THREAD

**Issue by odorisioe** [krakenjs/kraken-js#467]
U have an URL [POST] where I want to back a JSON with messages.
How I can translate the messages on the server side? Because I found that makara works only with dustjs.
Thanks

**Comment by odorisioe** [comment]
I close it. I used like example lib/getBundle.js in https://github.com/krakenjs/kraken-example-with-shoppingcart

**Comment by grawk** [comment]
Thanks! was going to point you that way :)
