### ISSUE TITLE
Passing variables to Kraken error middleware

### ISSUE THREAD

**Issue by xShirase** [krakenjs/kraken-js#468]
I was wondering how to pass a model to middleware 404 and 500? The reason being that my templates need a bunch of dust variables (prod/dev, assets on different cdns, etc) which are all defined in config and passed to the relevant model. It's a single page app, so it's all good except for the error pages.

example :

```
router.get('*', function(req, res, next){
        var env = req.app.kraken.get('env:env');
        model.cloudfront = req.app.kraken.get('aws:cloudfront_URL');
        model.version = req.app.kraken.get('version:current');
        if (env === 'production') {
            model.production = 1;
        } else if (env === 'staging') {
            model.staging = 1;
        }
        var maintenance = req.app.kraken.get('maintenanceMode:state');
        if(maintenance){
            model = new maintenanceModeModel();
            console.log('maintenance Mode on');
            res.render('maintenanceMode',model);
        }else{
            next();
        }
});
```

Is there a way to pass an object to the default middleware, or do I have to make custom routes to handle the errors?

**Comment by subeeshcbabu** [comment]
`404` and `500` middleware are already deprecated. See https://github.com/krakenjs/kraken-js/issues/359. You should be writing these error handlers as a standard practice (that will provide you more flexibility and control).

**Comment by grawk** [comment]
answered
