### ISSUE TITLE
Anybody tried Angular2 along with krakenjs ?

### ISSUE THREAD

**Issue by tomalex0** [krakenjs/kraken-js#471]
Would like to take a look into the code structure of angular2 witn krakenjs. 

I'm pretty much new  to  angular2. Please do  share if anybody is having sample project.

**Comment by tomalex0** [comment]
Was able to setup after multiple try, had to mix  gulp and grunt for now. Will try to  share once i have  proper code.

**Comment by ratul-roy** [comment]
Hi, Could you please share the github url  for Kraken + Angualr 2 ?

**Comment by subeeshcbabu** [comment]
@ratul-roy Check this out - https://github.com/subeeshcbabu/krakenjs-angular2
