### ISSUE TITLE
kraken0@india.com

### ISSUE THREAD

**Issue by githubxun** [krakenjs/kraken-js#479]
ask a question, Do you have this person in your team? His mailbox is "kraken0@india.com" .
This guy's banner kraken, Attacked our service and asked us to 0.1btc.

**Comment by shaunwarman** [comment]
Definitely not. Looks malicious.

**Comment by githubxun** [comment]
Too shameful, but fortunately, we have data backup. This is too humble personality

**Comment by githubxun** [comment]
I know that many of the company's databases were attacked yesterday and maliciously deleted the data

**Comment by shaunwarman** [comment]
Yes, the mongoDB ransomware. It looks like a shared list has `kraken0@india.com` as one of the known attacker emails.
