### ISSUE TITLE
[BARRIER] Build Tools needed for Getting Started

### ISSUE THREAD

**Issue by lazaridis-com** [krakenjs/kraken-js#483]
http://krakenjs.com/#getting-started

```
In order for the npm install command to work, you need these essential build tools:

    Python 2.6 or 2.7
    C++ compiler (GCC 4.2 or newer)
    Make

The method of installing these pre-requisites will vary by operating system.
```

This is an Entry-Barrier, which should be removed at all cost.

**Comment by shaunwarman** [comment]
Hey @lazaridis-com 

Thanks for the comment. This is common among node installations as native (c++) addons are built using a tool called [`node-gyp`](https://github.com/nodejs/node-gyp#installation). You can see the pre-requisites for some of the dependencies you mentioned. 

The need for `python` will potentially be removed in the future with the use of `gyp.js` by some recent work you can see [here](https://github.com/indutny/gyp.js). You can see an open issue and discussion the topic [here](https://github.com/nodejs/node-gyp/issues/960).

**Comment by lazaridis-com** [comment]
@shaunwarman , thanks for the technical explanations, which I understand.

As the Kraken Product Managemer, I would say to the fine team:

"Prioritize this please, we must get this barrier away, so Kraken gets adopted easier. We need a 15 min. quick-start, like other frameworks".

As the Kraken Project Manager, I would say:

"get 30 min. per day on this issue, until solved" or "allocate one day per week for this, until solved"

Its really important.

-

(I'm currently off-code, otherwise I would dive-in myself a bit)

**Comment by lazaridis-com** [comment]
btw.: not much activity here in the last 2 years...

**Comment by um-wat** [comment]
https://web.archive.org/web/20060913000000/http://en.wikipedia.org/wiki/Ilias_Lazaridis

**Comment by lazaridis-com** [comment]
@shaunwarman , what is the actual status of the project? Any public info on this?

**Comment by lazaridis-com** [comment]
depends on nodejs/node-gyp#960

**Comment by grawk** [comment]
Not sure what you mean "actual status of the project" @lazaridis-com 

It is an open source project. It is currently being used by PayPal to serve many millions of requests per day. I can't speak as well to its use outside of PayPal. I wish we had more resources focused on public adoption and tracking of that. But currently we do not.

With respect to this specific issue, this "barrier" exists for essentially any non-trivial nodejs module. We don't consider it as a problem we need to address for kraken specifically.

**Comment by lazaridis-com** [comment]
@grawk, thanks for the clarifications.
