### ISSUE TITLE
Issue with last update of makara-languagepackpath

### ISSUE THREAD

**Issue by saccodd** [krakenjs/kraken-js#487]
Last update of makara-languagepackpath from 1.1.0 to 1.1.1 throws the following error:

Possibly unhandled TypeError: Cannot read property 'localeContext' of undefined
    at module.exports.middleware

**Comment by gabrielcsapo** [comment]
@saccodd would you be able to open this issue up here https://github.com/krakenjs/makara-languagepackpath

**Comment by saccodd** [comment]
Ops sorry. Sure!
