### ISSUE TITLE
Uglify-js has security issues

### ISSUE THREAD

**Issue by BrandonCopley** [krakenjs/kraken-js#491]
uglify js in version <= 2.4.23 has some bugs minifying non-boolean comparisons. Upgrading uglify-js should solve this. It should be an easy fix and upgrade to npm.

**Comment by gabrielcsapo** [comment]
I do not see any entry for uglifyjs in the package.json https://github.com/krakenjs/kraken-js/blob/v2.x/package.json please update if you are seeing it somewhere else.
