### ISSUE TITLE
Templates in public directory?

### ISSUE THREAD

**Issue by blowsie** [krakenjs/kraken-js#492]
Excuse me for my lack of experience with Kraken but.. 

Today I started using Kraken and noticed the templates are pushed to the `./build` folder, and as a result the templates are accessible from the browser.

Is there a reason for this?  I tried looking in existing issues but could not find any answer.
The closest discussion i could see was this.
https://github.com/krakenjs/kraken-js/issues/335

Ultimately my concern here is that source code (_OK, only templates.. but still.._) is being exposed to the public.

Is there a way to prevent this?

**Comment by grawk** [comment]
Presumably you are using a generator-generated application?

You can control where, and if, templates are built to the .build directory via the grunt task configurations.

The reason they are put there, and accessible as static assets, is that you may want to render views on the client side. It's a fairly common use case.

**Comment by blowsie** [comment]
@grawk Yes i used the yo generator. Thanks for the info ill change my configs.
