### ISSUE TITLE
remove bluebird 🔥

### ISSUE THREAD

**Issue by gabrielcsapo** [krakenjs/kraken-js#494]
With native promise support we can easily move away from bluebird to get a nice performance boost for install and promisify functionality. 

[1] https://nodejs.org/api/util.html#util_util_promisify_original

**Comment by xjamundx** [comment]
YES!

**Comment by tlivings** [comment]
Where’s the PR? ;)

**Comment by DeadcatDev** [comment]
I don't get it. Bluebird promises are still the fastest ones, how do You want get perf boost kicking them?

**Comment by gabrielcsapo** [comment]
@DeadcatDev if you look at the use cases for bluebird in kraken, it is to use promisify and deferred, two places. The speed perfs you are talking about do exist, but as node continues native promises will only get better. Bringinging in another package is a cost that I don’t think is mandated by these use cases discussed.

**Comment by osukaa** [comment]
Removing bluebird and moving to native promises would require a major bump, since `util.promisify` is only supported on node >= 8
