### ISSUE TITLE
Is it alive?

### ISSUE THREAD

**Issue by DeadcatDev** [krakenjs/kraken-js#496]
Simple question - will KrakenJs be maintained and updated in future or not?

**Comment by tlivings** [comment]
There have been a few other questions like this and I think this answer is still relevant:

https://github.com/krakenjs/kraken-js/issues/414

**Comment by gabrielcsapo** [comment]
@DeadcatDev we are working to revamp our efforts and start publishing and updating kraken-js soon.  (hopefully publishing a new release today)

**Comment by gabrielcsapo** [comment]
just published a minor, https://github.com/krakenjs/kraken-js/releases/tag/2.2.0 we are coming back!
