### ISSUE TITLE
remove domains?

### ISSUE THREAD

**Issue by aheckmann** [krakenjs/kraken-js#502]
When working on reducing a memory leak related to domains we began [discussing potentially removing domains altogether](https://github.com/krakenjs/kraken-js/pull/499). Moving that conversation here.

**Comment by aheckmann** [comment]
[Here is the NodeJS domains post-mortem](https://nodejs.org/en/docs/guides/domain-postmortem/). After reading, I'm in favor of sacrificing the rare debugging assistance using domains provides and removing them from kraken.

**Comment by aheckmann** [comment]
Hapi has removed domains too: https://github.com/hapijs/hapi/issues/3573

**Comment by aheckmann** [comment]
[NodeJS discussion](https://github.com/nodejs/node/issues/16098) of using async_hooks and documentation / best practices plans. It's still the early days for a full replacement.

**Comment by shaunwarman** [comment]
Right, core seems to be in the move to [`async_hooks`](https://nodejs.org/api/async_hooks.html#async_hooks_async_hooks), but it doesn't seem like there is a concrete directions, especially with [`async_hooks`](https://nodejs.org/api/async_hooks.html#async_hooks_async_hooks) still in experimental phase.

**Comment by aheckmann** [comment]
Correct, a solid alternative is not there yet. However, domains don't even work properly as is. The more I research them and the related problems they are giving the app I'm analyzing, the more I never ever want to use them anywhere again. If I were starting a new NodeJS project, I would not use Kraken because it, by default, enables the use of the broken domain design. Nor can I confidently recommend using Kraken to anyone for the same reason. The kraken docs don't warn about their use AFAIK. I therefore don't trust the project. 

With alternative solutions available which support async/await style + try/catch error handling models, it's a no brainier for me.

**Comment by aheckmann** [comment]
[Restify deprecated functionality utilizing domains](https://github.com/restify/node-restify/blob/8f1816621b58637aae6b1fad7a4f6e5a27cc620d/lib/deprecationWarnings.js#L8-L13).

**Comment by shaunwarman** [comment]
Ya, I wouldn't mind a deprecation warning now and a major bump for `3` with removal and some thought out upgrades. 

Also, does it even make sense to sprinkle upgrades within the current setup or to move the underlying framework from express to something like [koa](http://koajs.com/)? Which brings a lot of work in another direction to get the error handling benefits and a potential solution. 

I mainly bring this up as there does seem to be a window right now where error handling is a problem with no concrete solution in current setup with domain deprecation and async hooks in an experimental stage.

**Comment by aheckmann** [comment]
Deprecation sounds good to me too.

The best path forward IMO is using an async/await + promises + try/catch
approach because it's easy to reason about. A few years ago we built all
our services at another company using koa with that model and were very
pleased. There is a small curve for people coming from express but the team
adjusted quickly. I'm not saying koa is better than anything else (there
are probably other good/better frameworks around now too), I'm saying the
error handling and middleware model is easy to reason about. In JS, error
handling is likely to remain a bit of a mess forever but try/await/catch
makes for improved comprehension. I probably won't have more feedback on
that bigger topic of swapping cores out until sometime in January.

**Comment by tlivings** [comment]
Given that deprecation warning was merged, assuming this is safe to close.

**Comment by aheckmann** [comment]
I'd prefer to leave it open until we remove domains.

**Comment by tlivings** [comment]
I don’t think domains deal with a “rare” use case. Until they are replaced with something of equivalent functionality, or express wraps the entire request chain in a promise, there will be a need for this.

**Comment by aheckmann** [comment]
> wraps the entire request chain in a promise

Async/Await. These days, enterprise quality frameworks should be built on
async/await. I think we need a new version a Kraken, maybe rewritten on top
of Koa.

**Comment by tlivings** [comment]
I’d be surprised if express didn’t have some plan for async/await support. Hapi 17 went this direction and it seems natural for this to be the next evolution of express.

**Comment by aheckmann** [comment]
Express authors went that direction years ago with Koa. But yeah, if
express wants to survive IMO, it needs a major breaking change. May as well
use Koa now.

**Comment by tlivings** [comment]
Koa is a different framework TJ Holowaychuk build that would not be compatible with kraken without a major rewrite. 

Express is still maintained and being developed.

**Comment by aheckmann** [comment]
That's what I've been trying to say. Async await changes things for the
better.
