### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by cyberious** [krakenjs/kraken-js#511]
Was looking at frameworks and this one seems to be dead. Is it?

**Comment by grawk** [comment]
PayPal uses Kraken.js for all of its node.js web applications. As such, it is not "dead".

There has not been an urgent need to add features, thus the activity to the module in open source is not that much.

There may be a release soon to address some potential issues with using [Domain](https://nodejs.org/api/domain.html) to run the middleware chain.

**Comment by charliecech** [comment]
@grawk You are right Kraken.js is a very well structured functional module that for the moment has not seen the urgent need for new features but why have not updated the package.json?

**Comment by cyberious** [comment]
Features sure, but there are a bunch of tickets that are potential bugs and have been around for a while, doesn't seem to be any desire to fix them unless PayPal is impacted. There was a comment back in June on another ticket about new triage process? Has that happened yet?

**Comment by brakon** [comment]
From what I've seen kraken does not start up on Node versions higher than v10 due to an issue with their Adaro, does this mean Paypal is using an old version of Node?

**Comment by snowinferno** [comment]
@brakon I'm able to run kraken apps without issue in Node v12. Perhaps there is something in your configuration or other modules that is causing your issue?

```
$ npm ls adaro
<project name redacted>
└─┬ makara@2.0.3
  └── adaro@1.0.4
```
```
$ npm ls kraken-js
<project name redacted>
└── kraken-js@2.2.0
```

**Comment by grawk** [comment]
not dead
